ceramicnetwork/rust-ceramic

- Cargo.lock
- ceramic-kubo-rpc/Cargo.toml
- ceramic-kubo-rpc/src/block.rs
- ceramic-kubo-rpc/src/http/block.rs
- ceramic-kubo-rpc/src/http/dag.rs
- ceramic-kubo-rpc/src/http/mod.rs
- ceramic-kubo-rpc/src/http/pubsub.rs
- ceramic-kubo-rpc/src/lib.rs
Adds endpoints for direct storage and retrieval of blocks.
> feat: add block endpoints

- core/src/jws.rs
- core/src/lib.rs
- event/src/args.rs
Adds missing derives or functions as necessary. Fixes issue with id set incorrectly in update.
> fix: Work correctly with http client

- .github/workflows/publish.yml
Github Actions needs an explicit step to enable buildx
> chore: setup docker buildx for Github Actions 

- api/src/server.rs
- core/src/event_id.rs
- core/src/interest.rs
- one/Cargo.toml
- one/src/main.rs
- one/src/network.rs
- p2p/src/config.rs
- p2p/src/node.rs
- recon/src/lib.rs
- recon/src/libp2p/protocol.rs
- recon/src/libp2p/tests.rs
- recon/src/recon.rs
- recon/src/recon/sqlitestore.rs
- recon/src/recon/tests.rs
- recon/src/sha256a.rs
This change includes various bug fixes found when trying to synchronize two nodes each with 32K unique events.
> feat: Recon kilo test fixes

- kubo-rpc/src/lib.rs
- recon/src/recon.rs
Stop dividing if we have 32k keys.
> feat: msg-size

- Cargo.lock
- core/Cargo.toml
- core/src/jws.rs
- core/src/lib.rs
- core/src/signer.rs
- event/src/args.rs
- event/src/event.rs
Adds necessary functionality to support dApps with the http client. This functionality is
* Ability to set a custom signer, for use with browser wallets
* Ability to create JWS for non CID payloads
> feat: dapp functionality

- core/src/stream_id.rs
Small improvement to stream type enum to support all type from the spec.
> fix: update stream type for all supported types

- recon/src/recon/sqlitestore.rs
Adds optimized implementation of first_and_last that uses a single query to get the data.
> fix: use single sql query to get first and last

- api/src/server.rs
We did this during Rust office hours as we learned about pattern matching.
> refactor: update if let into match for readability

- one/src/main.rs
Recon is off by default.
The behavior is that the Ceramic API will still allow you to create and read events. However Recon will not be used to synchronize events with peers. Any attempts from peers to do a Recon sync will be rejected.
> feat: add switch to disable/enable Recon

- .gitignore
- Cargo.lock
- Cargo.toml
- README.md
- cspell.json
- kubo-rpc-server/README.md
- kubo-rpc-server/api/openapi.yaml
- kubo-rpc-server/docs/default_api.md
- kubo-rpc-server/examples/server/server.rs
- kubo-rpc-server/src/lib.rs
- kubo-rpc/Cargo.toml
- kubo-rpc/kubo-rpc.yaml
- kubo-rpc/src/lib.rs
- one/Cargo.toml
- one/src/main.rs
- one/src/network.rs
- p2p/Cargo.toml
- p2p/src/behaviour.rs
- p2p/src/bin/migration.rs
- p2p/src/config.rs
- p2p/src/lib.rs
- p2p/src/node.rs
- p2p/src/sqliteblockstore.rs
- p2p/src/swarm.rs
- recon/Cargo.toml
- recon/src/recon/sqlitestore.rs
> feat: sqlite blockstore

- .github/workflows/release.yml
- api-server/README.md
- api-server/api/openapi.yaml
- api-server/src/models.rs
- api/ceramic.yaml
- api/release.toml
- beetle/iroh-bitswap/Cargo.toml
- beetle/iroh-car/Cargo.toml
- beetle/iroh-metrics/Cargo.toml
- beetle/iroh-rpc-client/Cargo.toml
- beetle/iroh-rpc-types/Cargo.toml
- beetle/iroh-store/Cargo.toml
- beetle/iroh-util/Cargo.toml
- ci-scripts/release.sh
- kubo-rpc/release.toml
- release.toml
Exclude iroh packages, and make sure correct yamls are replaced in api-server and kubo-rpc-server. Don't replace example version.
> fix: release

- .github/workflows/release.yml
Verified on mac, so hopefully this works
> fix: just use star for cleanup

- p2p/src/sqliteblockstore.rs
With this fix I see the ceramic-tests property tests passing consistently :) Also adds a test for the previous fix about missing blocks.
> fix: return v1 cid when fetching blocks

- Cargo.lock
- README.md
- cspell.json
- p2p/Cargo.toml
- p2p/src/bin/migration.rs
- p2p/src/sqliteblockstore.rs
Support reading in from an external SQLite file in to your ceramic data store.
> feat: merge-from-sqlite

- one/src/lib.rs
bootstrap peers for Mainnet, TestnetClay, and DevUnstable from
https://github.com/ceramicnetwork/
js-ceramic/blob/develop/packages/ipfs-topology/src/ipfs-topology.ts
> feat: bootstrap peers

- one/src/lib.rs
- p2p/src/config.rs
I expect that we will need to adjust these limits experimentally. So for now I have exposed all limit config directly. If we find that there are values that work for nearly all situations we can remove the options and hard code that value.
> feat: add cli opts for connection limits

- kubo-rpc/src/lib.rs
- p2p/src/sqliteblockstore.rs
Prior to this change any  IPFS put call would publish to the DHT. Now if we already knew stored the block we do not publish as it is assumed the republish logic will handle that work.
> fix: only provide records on the DHT when they are new

- metrics/src/lib.rs
Prior to this change JSON fields from spans would produce an error in the logs. Apparently there are two kinds of formats, one for events and one for fields. We need to configure both and they need to align in order for JSON fields to work properly. This change adds a wrapping type to help with this.
> fix: fix JSON log format errors

- p2p/src/metrics.rs
- p2p/src/publisher.rs
These metrics were already in the structured logs. Turns out they are quite useful so I added them as actual metrics.
> feat: add publisher batch metrics

- beetle/iroh-bitswap/src/handler.rs
- beetle/iroh-bitswap/src/lib.rs
This change updates several logs statements to use proper fields for the logs and adds peer_id context to the inbound_substream and outbound_substream functions.
> refactor: update bitswap logs to use structured logging

- .cargo/config.toml
- Cargo.lock
- one/Cargo.toml
- one/src/lib.rs
With this change now basic metrics about the tokio runtime are included with the set of Prometheus metrics.
> feat: add tokio metrics

- kubo-rpc/src/http.rs
- recon/src/recon/sqlitestore.rs
Make clippy happy by accessing first element with first.
> fix: clippy accessing first element with first

- .github/workflows/publish.yml
CD for pre-release and release. 
PR currently for testing CD. 
Tests: 
1) Merge to main and create tags on creation of release tags workflow should get trigered.
> feat: on tag publish deploy to envs

- .github/workflows/publish-prerelease.yml
> fix: naming

- Dockerfile
> chore: use docker root user

- store/src/sqlite/model.rs
Previous behavior was to error if an event and its value were inserted twice. Now we simply drop a value if we already have a value. This assumes that keys always point to the same value which is the base assumption of recon itself.
> fix: allow double insert of key/value pairs in Recon

- recon/src/protocol.rs
Prior to this change all initial interest ranges requests were sent to the remote potentially deadlocking the protocol. Now anytime the initiator sends a RangeRequest to the responder it always checks the pending ranges limit.
> fix: honor PENDING_RANGES_LIMIT for initial ranges

- Cargo.lock
- Cargo.toml
- beetle/iroh-bitswap/Cargo.toml
- beetle/iroh-bitswap/benches/message.rs
- beetle/iroh-car/src/lib.rs
- p2p/Cargo.toml
- p2p/benches/lru_cache.rs
- recon/src/libp2p/tests.rs
- store/Cargo.toml
- store/benches/sqlite_store.rs
Use criterion to benchmark store inserts
> feat: store bench

- api-server/README.md
- api-server/api/openapi.yaml
- api-server/src/client/mod.rs
- api-server/src/lib.rs
- api-server/src/server/mod.rs
- api/ceramic.yaml
- api/src/server.rs
Add bad request response to GET events API and improve event creation 400 response.
> chore: add bad request response to get events API

- .github/workflows/rust-build-and-test.yml
Correctness tests should be cleaned up sooner.
> fix: lower correctness test network ttl

- api-server/.openapi-generator/FILES
- api-server/README.md
- api-server/api/openapi.yaml
- api-server/docs/InterestsGet.md
- api-server/docs/InterestsGetInterests.md
- api-server/docs/InterestsGetInterestsInner.md
- api-server/docs/default_api.md
- api-server/examples/client/main.rs
- api-server/examples/server/server.rs
- api-server/src/client/mod.rs
- api-server/src/lib.rs
- api-server/src/models.rs
- api-server/src/server/mod.rs
- api/ceramic.yaml
- api/src/metrics/api.rs
- api/src/server.rs
- api/src/tests.rs
Added `GET /experimental/interests` endpoint to help debugging.
> feat: add interests endpoint for inspecting interests of a node

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- api-server/Cargo.toml
- api-server/README.md
- api-server/api/openapi.yaml
- api-server/src/lib.rs
- api/ceramic.yaml
- kubo-rpc-server/Cargo.toml
- kubo-rpc-server/README.md
- kubo-rpc-server/api/openapi.yaml
- kubo-rpc-server/src/lib.rs
- kubo-rpc/kubo-rpc.yaml
- Adjust prom metrics to capture path info and status codes  (#364)
- Disallow events with unexpected fields via the http api (#363)
- Rename store traits to InterestStore and EventStore (#365)
- Deserialize CAR into Event before extracting EventID. (#362)
> chore: version v0.21.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- api-server/Cargo.toml
- api-server/README.md
- api-server/api/openapi.yaml
- api-server/src/lib.rs
- api/ceramic.yaml
- kubo-rpc-server/Cargo.toml
- kubo-rpc-server/README.md
- kubo-rpc-server/api/openapi.yaml
- kubo-rpc-server/src/lib.rs
- kubo-rpc/kubo-rpc.yaml
- Cd to dev (#376)
- Add builder for time events (#378)
- Add cacao serde to unvalidated::Events (#380)
- Consolidate car serde logic into event crate (#379)
- Run clippy fix (#377)
- Minor clean up and derive more behavior on events (#381)
> chore: version v0.23.0

- event/src/unvalidated/builder.rs
- event/src/unvalidated/event.rs
New approach instead of https://github.com/ceramicnetwork/rust-ceramic/pull/385
> fix: TimeEvents from single-write anchor batches don't have a separate root block

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- api-server/Cargo.toml
- api-server/README.md
- api-server/api/openapi.yaml
- api-server/src/lib.rs
- api/ceramic.yaml
- kubo-rpc-server/Cargo.toml
- kubo-rpc-server/README.md
- kubo-rpc-server/api/openapi.yaml
- kubo-rpc-server/src/lib.rs
- kubo-rpc/kubo-rpc.yaml
- Remove redundant db url cli arg (#384)
- TimeEvents from single-write anchor batches don't have a separate root block (#386)
> chore: version v0.24.0

- CONTRIBUTING.md
- README.md
1. Moves contributing, packaging, and releasing into a separate CONTRIBUTING.md file
2. Includes installation guide for mac and linux
3. Includes docker guides
> chore: Mzk/readme installation

- one/src/lib.rs
- one/src/migrations.rs
Additionally the log init code was moved before the sq db code so that we can use normal tracing for the db init code.
> feat: add log-format option to migrations command

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- api-server/Cargo.toml
- api-server/README.md
- api-server/api/openapi.yaml
- api-server/src/lib.rs
- api/ceramic.yaml
- kubo-rpc-server/Cargo.toml
- kubo-rpc-server/README.md
- kubo-rpc-server/api/openapi.yaml
- kubo-rpc-server/src/lib.rs
- kubo-rpc/kubo-rpc.yaml
- Add debug to all event types (#432)
- Release archive with linux binary (#422)
- Update selector for post-deployment tests (#435)
> chore: version v0.28.1

- README.md
- UPGRADE.md
> docs: adds UPGRADE.md docs

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- api-server/Cargo.toml
- api-server/README.md
- api-server/api/openapi.yaml
- api-server/src/lib.rs
- api/ceramic.yaml
- kubo-rpc-server/Cargo.toml
- kubo-rpc-server/README.md
- kubo-rpc-server/api/openapi.yaml
- kubo-rpc-server/src/lib.rs
- kubo-rpc/kubo-rpc.yaml
- Support cors via cli flag (#425)
- Workflow update deb repo (#437)
- Add option for external swarm addresses (#439)
- Add context to p2p key dir errors (#438)
- Adds UPGRADE.md docs (#402)
- Add CODEOWNERS file (#443)
> chore: version v0.29.0

- store/benches/sqlite_store.rs
It compiles again and now supports a batch insert (currently 10). Reducing the locking by increasing the batch size improved performance quite a bit, but it's a bit contrived.
```
small model inserts/sqlite store
time:   [586.76 ms 591.17 ms 596.27 ms]
change: [−42.061% −41.437% −40.927%] (p = 0.00 < 0.05)
Performance has improved.
Found 2 outliers among 10 measurements (20.00%)
1 (10.00%) low mild
1 (10.00%) high severe
Benchmarking large model inserts/sqlite store: Warming up for 30.000 s
Warning: Unable to complete 10 samples in 60.0s. You may wish to increase target time to 67.2s or enable flat sampling.
large model inserts/sqlite store
time:   [633.02 ms 645.51 ms 662.29 ms]
change: [−43.422% −42.661% −41.755%] (p = 0.00 < 0.05)
Performance has improved.
```
> fix: fix benchmark and support batch inserts

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- api-server/Cargo.toml
- api-server/README.md
- api-server/api/openapi.yaml
- api-server/src/lib.rs
- api/ceramic.yaml
- kubo-rpc-server/Cargo.toml
- kubo-rpc-server/README.md
- kubo-rpc-server/api/openapi.yaml
- kubo-rpc-server/src/lib.rs
- kubo-rpc/kubo-rpc.yaml
- Feature and experimental feature flags (#448)
- Change default dir back to shared home location (#471)
> chore: version v0.32.0

- service/src/event/migration.rs
TileDocument init events are not required to have a data field, in which case they must have a header field. TileDocument data events are opposite, they are required to have a data field and the header field is optional.
> fix: add better TileDocument detection

- service/src/event/order_events.rs
small cleanup, no functional change
> chore: Remove an iteration pass in OrderEvents::try_new

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- api-server/Cargo.toml
- api-server/README.md
- api-server/api/openapi.yaml
- api-server/src/lib.rs
- api/ceramic.yaml
- kubo-rpc-server/Cargo.toml
- kubo-rpc-server/README.md
- kubo-rpc-server/api/openapi.yaml
- kubo-rpc-server/src/lib.rs
- kubo-rpc/kubo-rpc.yaml
- Recon event insert batching (#470)
- Modify recon store to support event validation concepts (#473)
- Add noop ceramic-olap binary (#482)
- Add better TileDocument detection (#475)
- Fix bug in TimeEvent witness blocks parsing logic (#486)
- Create sync car crate (#485)
- Flatten EventInsertable type (#480)
- Remove Clone from EventInsertable (#481)
- Change EventInsertable to store the parsed Event object instead of its raw blocks (#487)
- Remove an iteration pass in OrderEvents::try_new (#489)
- Add TODO comment (#491)
- Remove EventMetadata type (#490)
> chore: version v0.33.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- api-server/Cargo.toml
- api-server/README.md
- api-server/api/openapi.yaml
- api-server/src/lib.rs
- api/ceramic.yaml
- kubo-rpc-server/Cargo.toml
- kubo-rpc-server/README.md
- kubo-rpc-server/api/openapi.yaml
- kubo-rpc-server/src/lib.rs
- kubo-rpc/kubo-rpc.yaml
- Eth and sol pkh cacao validation (#496)
- Jws signature validation (#498)
- Check cacao resources against stream information (#502)
- Use cacao timestamp strings and parse (#504)
- Add logic to dispatch validation based on event type (#493)
- Modify cacao, unvalidated module, jwk to add functionality needed for event validation (#492)
> chore: version v0.34.0

- Cargo.lock
- Cargo.toml
Update console-subscriber package version
> chore: update console-subscriber package version

- CODEOWNERS
- Cargo.lock
- Cargo.toml
- Makefile
- anchor-service/Cargo.toml
- anchor-service/src/anchor.rs
- anchor-service/src/anchor_batch.rs
- anchor-service/src/lib.rs
- anchor-service/src/merkle_tree.rs
- anchor-service/src/time_event.rs
- anchor-service/src/transaction_manager.rs
- cspell.json
- event-svc/src/store/sql/entities/event_block.rs
- event/src/lib.rs
- event/src/unvalidated/event.rs
This is the first PR for self-anchoring and includes:
- Anchor service machinery
- Merkle tree building
- Time Event building
- Traits for:
- Anchor client (e.g. Event Service)
- Transaction managers (e.g. remote CAS)
> feat: anchor service (part 2)

- olap/src/aggregator/ceramic_patch.rs
Had this locally and forgot to push before merging the first PR.
> refactor: small logic change for readability

- one/src/daemon.rs
Make all self-anchoring config options experimental.
> fix: make self-anchoring config experimental

- Cargo.lock
- anchor-service/Cargo.toml
- anchor-service/src/anchor_batch.rs
Process batch in a fixed interval
> feat: process batches on the interval

- Dockerfile
Eth RPC failed to connect, now it connects.
> chore: update ca-certificates in image build

- Cargo.lock
- Cargo.toml
- flight/src/server.rs
Disables all types of SQL queries except read only queries.
> feat: protect FlightSQL server with sql options.

- event-svc/src/store/metrics.rs
We insert in batches that  are typically 3-100 items (depending if it's api or recon). This gives a better sense of how long each item takes in comparison to the duration of the entire request. It's kind of a clunky way to do this, but I didn't want to return a duration from the other function and then record a second item, but maybe that would be cleaner.
> chore: record the per item duration of an insert_many request

- README.md
Tested, now the url is correct
> fix: correct path to latest tarball

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- api-server/Cargo.toml
- api-server/README.md
- api-server/api/openapi.yaml
- api-server/src/lib.rs
- api/ceramic.yaml
- kubo-rpc-server/Cargo.toml
- kubo-rpc-server/README.md
- kubo-rpc-server/api/openapi.yaml
- kubo-rpc-server/src/lib.rs
- kubo-rpc/kubo-rpc.yaml
- Remove superflous $ in cacao model auth check (#573)
- Make error message match the js-ceramic version (#574)
> chore: version v0.41.1

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- api-server/Cargo.toml
- api-server/README.md
- api-server/api/openapi.yaml
- api-server/src/lib.rs
- api/ceramic.yaml
- kubo-rpc-server/Cargo.toml
- kubo-rpc-server/README.md
- kubo-rpc-server/api/openapi.yaml
- kubo-rpc-server/src/lib.rs
- kubo-rpc/kubo-rpc.yaml
- Expose all tables via flight sql (#571)
- Use larger github runner for image builds (#577)
> chore: version v0.42.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- api-server/Cargo.toml
- api-server/README.md
- api-server/api/openapi.yaml
- api-server/src/lib.rs
- api/ceramic.yaml
- kubo-rpc-server/Cargo.toml
- kubo-rpc-server/README.md
- kubo-rpc-server/api/openapi.yaml
- kubo-rpc-server/src/lib.rs
- kubo-rpc/kubo-rpc.yaml
- Use cache table to make queries faster and writes to object store (#576)
- Update ci env to dev-qa cluster (#584)
> chore: version v0.43.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- api-server/Cargo.toml
- api-server/README.md
- api-server/api/openapi.yaml
- api-server/src/lib.rs
- api/ceramic.yaml
- kubo-rpc-server/Cargo.toml
- kubo-rpc-server/README.md
- kubo-rpc-server/api/openapi.yaml
- kubo-rpc-server/src/lib.rs
- kubo-rpc/kubo-rpc.yaml
- Backoff recon synchronization to peers with bad data (#597)
- Consistent pipeline table names and schemas (#587)
> chore: version v0.44.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- api-server/Cargo.toml
- api-server/README.md
- api-server/api/openapi.yaml
- api-server/src/lib.rs
- api/ceramic.yaml
- kubo-rpc-server/Cargo.toml
- kubo-rpc-server/README.md
- kubo-rpc-server/api/openapi.yaml
- kubo-rpc-server/src/lib.rs
- kubo-rpc/kubo-rpc.yaml
- Stop synchronizing interests ([#632](https://github.com/ceramicnetwork/rust-ceramic/issues/632))
- Use debug for peer dial failures ([#631](https://github.com/ceramicnetwork/rust-ceramic/issues/631))
> chore: version v0.47.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- api-server/Cargo.toml
- api-server/README.md
- api-server/api/openapi.yaml
- api-server/src/lib.rs
- api/ceramic.yaml
- kubo-rpc-server/Cargo.toml
- kubo-rpc-server/README.md
- kubo-rpc-server/api/openapi.yaml
- kubo-rpc-server/src/lib.rs
- kubo-rpc/kubo-rpc.yaml
- Shutdown ordering tasks with sigint ([#629](https://github.com/ceramicnetwork/rust-ceramic/issues/629))
- Use explicit os versions ([#634](https://github.com/ceramicnetwork/rust-ceramic/issues/634))
> chore: version v0.47.1

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- api-server/Cargo.toml
- api-server/README.md
- api-server/api/openapi.yaml
- api-server/src/lib.rs
- api/ceramic.yaml
- kubo-rpc-server/Cargo.toml
- kubo-rpc-server/README.md
- kubo-rpc-server/api/openapi.yaml
- kubo-rpc-server/src/lib.rs
- kubo-rpc/kubo-rpc.yaml
- Shutdown ordering tasks with sigint ([#629](https://github.com/ceramicnetwork/rust-ceramic/issues/629))
- Use explicit os versions ([#634](https://github.com/ceramicnetwork/rust-ceramic/issues/634))
- Version v0.47.1 ([#635](https://github.com/ceramicnetwork/rust-ceramic/issues/635))
- Fix issue in package script
> chore: version v0.47.2

- event-svc/benches/sqlite_store.rs
~~Cargo lockfile v4 is the default in rust 1.83 and has been supported since 1.78 (which is now our MSRV). Our metadata crate needed a dependency bump to work with this.~~ Handled in #641 
I fixed some compilation errors in the bench due to refactors.
> chore: fix bench compilation errors

- pipeline/src/cid_string.rs
Datafusion recently deprecated the invoke method on ScalarUDFs. This change updates to be following best practices going forward.
> fix: use invoke_batch on UDFs as invoke is deprecated

- pipeline/src/concluder/table.rs
Prior to this change the feed table implementation never returned more than 10K events. Now it batches by 10K events and returns up to the limit.
> fix: adds batching logic to conclusion-feed-table

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- api-server/Cargo.toml
- api-server/README.md
- api-server/api/openapi.yaml
- api-server/src/lib.rs
- api/ceramic.yaml
- kubo-rpc-server/Cargo.toml
- kubo-rpc-server/README.md
- kubo-rpc-server/api/openapi.yaml
- kubo-rpc-server/src/lib.rs
- kubo-rpc/kubo-rpc.yaml
- Schema validation ([#663](https://github.com/ceramicnetwork/rust-ceramic/issues/663))
> chore: version v0.52.0

- pipeline/src/aggregator/mod.rs
The distinct step when fetching pending events was to correct for the case when we failed to delete old pending events. However it was prohibitively expensive consuming many GBs of memory for roughly 200K pending event rows.
There are few reasons why the distinct was too aggregisve and no the best solution to the duplicate problem.
1. While duplicate pending events can arise seeing the same model cid twice is not possible. This means that in worst case scenario pending events get processed once but fail to be deleted, in which case they remain in the pending events table forever. But those duplicates will not result in event state rows
2. With retries (now added) the likely hood of duplicates pending events is very small and not worth paying the de-duplication cost on every read of the …
> fix: remove distinct step as its prohibitively expensive

- pipeline/src/aggregator/model_instance_patch.rs
- pipeline/src/aggregator/model_patch.rs
With this change events with bad patches or data will just end up with null states instead of preventing the entire pipeline from processing more data.
> fix: make apply patch not fail the pipeline

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- api-server/Cargo.toml
- api-server/README.md
- api-server/api/openapi.yaml
- api-server/src/lib.rs
- api/ceramic.yaml
- kubo-rpc-server/Cargo.toml
- kubo-rpc-server/README.md
- kubo-rpc-server/api/openapi.yaml
- kubo-rpc-server/src/lib.rs
- kubo-rpc/kubo-rpc.yaml
- Make apply patch not fail the pipeline ([#690](https://github.com/ceramicnetwork/rust-ceramic/issues/690))
- Add CI workflows to publish sdk ([#689](https://github.com/ceramicnetwork/rust-ceramic/issues/689))
> chore: version v0.54.1

- ci-scripts/sdk_release_pr.sh
- sdk/packages/events/package.json
- sdk/packages/flight-sql-client/npm/darwin-arm64/package.json
- sdk/packages/flight-sql-client/npm/darwin-x64/package.json
- sdk/packages/flight-sql-client/npm/linux-x64-gnu/package.json
- sdk/packages/flight-sql-client/package.json
- sdk/packages/http-client/package.json
- sdk/packages/identifiers/package.json
- sdk/packages/model-client/package.json
- sdk/packages/model-instance-client/package.json
- sdk/packages/model-instance-protocol/package.json
- sdk/packages/model-protocol/package.json
- sdk/packages/stream-client/package.json
- sdk/packages/test-utils/package.json
- sdk/packages/test-vectors/package.json
> chore(sdk): version v0.3.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- api-server/Cargo.toml
- api-server/README.md
- api-server/api/openapi.yaml
- api-server/src/lib.rs
- api/ceramic.yaml
- kubo-rpc-server/Cargo.toml
- kubo-rpc-server/README.md
- kubo-rpc-server/api/openapi.yaml
- kubo-rpc-server/src/lib.rs
- kubo-rpc/kubo-rpc.yaml
- Update the sdk repo url ([#696](https://github.com/ceramicnetwork/rust-ceramic/issues/696))
- *(sdk)* Version v0.3.0 ([#694](https://github.com/ceramicnetwork/rust-ceramic/issues/694))
> chore: version v0.54.2

- sdk/packages/events/package.json
- sdk/packages/flight-sql-client/npm/darwin-arm64/package.json
- sdk/packages/flight-sql-client/npm/darwin-x64/package.json
- sdk/packages/flight-sql-client/npm/linux-x64-gnu/package.json
- sdk/packages/flight-sql-client/package.json
- sdk/packages/http-client/package.json
- sdk/packages/identifiers/package.json
- sdk/packages/model-client/package.json
- sdk/packages/model-instance-client/package.json
- sdk/packages/model-instance-protocol/package.json
- sdk/packages/model-protocol/package.json
- sdk/packages/stream-client/package.json
- sdk/packages/test-utils/package.json
- sdk/packages/test-vectors/package.json
> chore(sdk): version v0.4.0

- sdk/packages/events/package.json
- sdk/packages/flight-sql-client/npm/darwin-arm64/package.json
- sdk/packages/flight-sql-client/npm/darwin-x64/package.json
- sdk/packages/flight-sql-client/npm/linux-x64-gnu/package.json
- sdk/packages/flight-sql-client/package.json
- sdk/packages/http-client/package.json
- sdk/packages/identifiers/package.json
- sdk/packages/model-client/package.json
- sdk/packages/model-instance-client/package.json
- sdk/packages/model-instance-protocol/package.json
- sdk/packages/model-protocol/package.json
- sdk/packages/stream-client/package.json
- sdk/packages/test-utils/package.json
- sdk/packages/test-vectors/package.json
> chore(sdk): version v0.6.0

- sdk/packages/events/package.json
- sdk/packages/flight-sql-client/npm/darwin-arm64/package.json
- sdk/packages/flight-sql-client/npm/darwin-x64/package.json
- sdk/packages/flight-sql-client/npm/linux-x64-gnu/package.json
- sdk/packages/flight-sql-client/package.json
- sdk/packages/http-client/package.json
- sdk/packages/identifiers/package.json
- sdk/packages/model-client/package.json
- sdk/packages/model-instance-client/package.json
- sdk/packages/model-instance-protocol/package.json
- sdk/packages/model-protocol/package.json
- sdk/packages/stream-client/package.json
- sdk/packages/test-utils/package.json
- sdk/packages/test-vectors/package.json
> chore(sdk): version v0.7.0

- sdk/packages/events/package.json
- sdk/packages/flight-sql-client/npm/darwin-arm64/package.json
- sdk/packages/flight-sql-client/npm/darwin-x64/package.json
- sdk/packages/flight-sql-client/npm/linux-x64-gnu/package.json
- sdk/packages/flight-sql-client/package.json
- sdk/packages/http-client/package.json
- sdk/packages/identifiers/package.json
- sdk/packages/model-client/package.json
- sdk/packages/model-instance-client/package.json
- sdk/packages/model-instance-protocol/package.json
- sdk/packages/model-protocol/package.json
- sdk/packages/stream-client/package.json
- sdk/packages/test-utils/package.json
- sdk/packages/test-vectors/package.json
> chore(sdk): version v0.8.0

- sdk/packages/events/package.json
- sdk/packages/flight-sql-client/npm/darwin-arm64/package.json
- sdk/packages/flight-sql-client/npm/darwin-x64/package.json
- sdk/packages/flight-sql-client/npm/linux-x64-gnu/package.json
- sdk/packages/flight-sql-client/package.json
- sdk/packages/http-client/package.json
- sdk/packages/identifiers/package.json
- sdk/packages/model-client/package.json
- sdk/packages/model-instance-client/package.json
- sdk/packages/model-instance-protocol/package.json
- sdk/packages/model-protocol/package.json
- sdk/packages/stream-client/package.json
- sdk/packages/test-utils/package.json
- sdk/packages/test-vectors/package.json
> chore(sdk): version v0.9.0

- sdk/packages/events/package.json
- sdk/packages/flight-sql-client/npm/darwin-arm64/package.json
- sdk/packages/flight-sql-client/npm/darwin-x64/package.json
- sdk/packages/flight-sql-client/npm/linux-x64-gnu/package.json
- sdk/packages/flight-sql-client/package.json
- sdk/packages/http-client/package.json
- sdk/packages/identifiers/package.json
- sdk/packages/model-client/package.json
- sdk/packages/model-instance-client/package.json
- sdk/packages/model-instance-protocol/package.json
- sdk/packages/model-protocol/package.json
- sdk/packages/stream-client/package.json
- sdk/packages/test-utils/package.json
- sdk/packages/test-vectors/package.json
> chore(sdk): version v0.10.0

- sdk/packages/events/package.json
- sdk/packages/flight-sql-client/npm/darwin-arm64/package.json
- sdk/packages/flight-sql-client/npm/darwin-x64/package.json
- sdk/packages/flight-sql-client/npm/linux-x64-gnu/package.json
- sdk/packages/flight-sql-client/package.json
- sdk/packages/http-client/package.json
- sdk/packages/identifiers/package.json
- sdk/packages/model-client/package.json
- sdk/packages/model-instance-client/package.json
- sdk/packages/model-instance-protocol/package.json
- sdk/packages/model-protocol/package.json
- sdk/packages/stream-client/package.json
- sdk/packages/test-utils/package.json
- sdk/packages/test-vectors/package.json
> chore(sdk): version v0.11.0
