Cargo.lock, Cargo.toml, Makefile, ceramic-kubo-rpc/Cargo.toml, ceramic-kubo-rpc/src/http/dag.rs, ceramic-kubo-rpc/src/http/mod.rs, ceramic-kubo-rpc/src/http/pubsub.rs, ceramic-kubo-rpc/src/http/swarm.rs, ceramic-kubo-rpc/src/lib.rs, ceramic-kubo-rpc/src/pubsub.rs
With this change the RPC implements listing subscribed topics and publishing/subscribing  messages to/from topics.
=> feat: add support for pubsub/* HTTP endpoints

ceramic-kubo-rpc/src/http/mod.rs, ceramic-kubo-rpc/src/http/pin.rs, ceramic-kubo-rpc/src/lib.rs, ceramic-kubo-rpc/src/pin.rs
Pin endpoints cheat. Beetle does not garbage collect items in its store. Therefore everything is implicitly pinned. As such an `add` operation is basically a `get` operation and a `remove` operation is a no-op.
=> feat: add pin endpoints

Cargo.lock, ceramic-kubo-rpc/src/dag.rs, ceramic-kubo-rpc/src/http/block.rs, ceramic-kubo-rpc/src/http/dag.rs, ceramic-kubo-rpc/src/http/id.rs, ceramic-kubo-rpc/src/http/mod.rs, ceramic-kubo-rpc/src/http/pin.rs, ceramic-kubo-rpc/src/http/pubsub.rs, ceramic-kubo-rpc/src/id.rs, ceramic-kubo-rpc/src/lib.rs, ceramic-kubo-rpc/src/pin.rs, ceramic-one/Cargo.toml, ceramic-one/src/main.rs
Prior to this change dag/get and dag/resolve requests could not follow links into DAG-JOSE encoded nodes. This is now supported by implementing a simple resolver.
Additionally the `id` endpoint has been added and various bugs fixes have been made.
=> feat: adds id endpoint and adds dag-jose resolving support

.dockerignore, .github/workflows/publish.yml, Dockerfile, Makefile, ci-scripts/publish.sh
This change adds a Dockerfile that builds an image to run the ceramic-one binary.
Additionally CI workflows are added to publish a new version of the image on pushes to main.
=> chore: add dockerfile for running ceramic-one

Cargo.lock, Cargo.toml, Dockerfile, kubo-rpc/Cargo.toml, kubo-rpc/src/swarm.rs, one/Cargo.toml, one/src/main.rs, one/src/metrics.rs, one/src/pubsub.rs
The `eye` command to the `ceramic-one` CLI starts a normal daemon and then subscribes to a gossipsub ceramic topic locally pinning any tips it learns about.
The `eye` behavior along with the existing metrics and traces has proven to be a useful tool to understand how ceramic-one is behaving.
=> feat: adds eye command

Cargo.lock, Cargo.toml, Dockerfile, kubo-rpc/Cargo.toml, kubo-rpc/src/block.rs, kubo-rpc/src/dag.rs, kubo-rpc/src/error.rs, kubo-rpc/src/http/block.rs, kubo-rpc/src/http/dag.rs, kubo-rpc/src/http/id.rs, kubo-rpc/src/http/mod.rs, kubo-rpc/src/http/pin.rs, kubo-rpc/src/http/pubsub.rs, kubo-rpc/src/http/swarm.rs, kubo-rpc/src/id.rs, kubo-rpc/src/lib.rs, kubo-rpc/src/pin.rs, kubo-rpc/src/pubsub.rs, kubo-rpc/src/swarm.rs, one/Cargo.toml, one/src/ipfs.rs, one/src/main.rs, one/src/metrics.rs
This change exposes a Prometheus /metrics endpoint to enable metric collection via scraping.
Additionally a refactor to the how Beetle is consumed was performed. It was becoming very time consuming to trace Beetle code paths through many unneeded abstractions (i.e. unixfs). As such the refactor means that we now consume a minimal set of dependent crates from Beetle.
This has the advantage that is now very clear how these systems interact. For example publishing DHT records or when/how IPLD blocks are added to the local store.
Specifically we now depend on:
* iroh-metrics
* iroh-p2p
* iroh-rpc-client
* iroh-rpc-types
* iroh-store
Previously we were dependent on:
* iroh-api
* iroh-bitswap
* iroh-car
* iroh-embed
* iroh-gateway
* iroh-metrics
* iroh-one
* iroh-p2p
* iroh-resolver
* …
=> feat: add /metrics endpoint

Dockerfile, Makefile, core/src/lib.rs, event/src/lib.rs, kubo-rpc/src/lib.rs, one/src/main.rs, recon/src/lib.rs
Additionally this change updates the Dockerfile to build using first class cache provided by Docker buildkit.
=> chore: only deny warnings during CI

Cargo.lock, Cargo.toml, Dockerfile, Makefile, kubo-rpc/src/http/pubsub.rs, one/Cargo.toml, one/src/main.rs, one/src/metrics.rs, one/src/network.rs, recon/Cargo.toml, recon/src/ahash.rs, recon/src/lib.rs, recon/src/libp2p.rs, recon/src/libp2p/handler.rs, recon/src/libp2p/protocol.rs, recon/src/libp2p/tests.rs, recon/src/recon/mod.rs, recon/src/recon/tests.rs
Implements Recon protocol over a network using libp2p. 
This PR contains some demo code to show how Recon works. The demo code generates random strings as keys for Recon. Each node then synchronizes those keys. Additionally each node adds a new random key to their set periodically. 
The behaviour currently attempts to sync to all peers for the entire key space and will restart synchronization 1 second after becoming in sync with a peer.
Anything about storing keys on disk is not covered in this PR.
TODO:
=> feat: implement libp2p Recon protocol

dev.yaml, one/src/main.rs, one/src/network.rs, p2p/src/behaviour.rs, p2p/src/node.rs, p2p/src/rpc.rs
With this change its now possible for Ceramic nodes to discover each
other when they are connected to the same DHT.
This PR depends on the refactor in #55. The refactor moves code from Beetle into this repo. This allows for the p2p `Node` code to be directly modified instead of attempting to expose API from the Node for these specific needs.
=> feat: add ceramic peer discovery 

p2p/src/node.rs, recon/src/ahash.rs, recon/src/eventid.rs, recon/src/libp2p.rs, recon/src/recon/mod.rs, recon/src/recon/tests.rs
Move recon from using stings to bytes for transport.
Update serde serialize
Use EventID in rust data structures.
=> feat: recon-bytes

Cargo.lock, Cargo.toml, api/src/lib.rs, api/src/server.rs, core/Cargo.toml, core/src/interest.rs, core/src/lib.rs, core/src/range.rs, one/src/main.rs, one/src/network.rs, p2p/src/behaviour.rs, p2p/src/node.rs, p2p/src/swarm.rs, recon/Cargo.toml, recon/src/lib.rs, recon/src/libp2p.rs, recon/src/libp2p/handler.rs, recon/src/libp2p/protocol.rs, recon/src/libp2p/stream_set.rs, recon/src/libp2p/tests.rs, recon/src/libp2p/upgrade.rs, recon/src/recon.rs, recon/src/recon/parser.lalrpop, recon/src/recon/tests.rs
With these changes ceramic-one can do the following:
1. Maintain a set of interest ranges for itself and other peers
2. Synchronize interest ranges among peers
3. Use Recon to sync keys that exist within intersecting interest ranges.
4. Update its local interest when a subscription is requested.
Some things that are still lacking:
1. Interests are not expired
2. Interests are never removed from the local node
3. Interests are NOT signed but still shared with peers transitively 
This PR is large enough, I suggest we create issues for the above and address them in subsequent smaller PRs.
=> feat: add interest synchronization and update Recon 

core/src/jwk.rs, core/src/signer.rs
Keramik needs signer to be signed. Will need a different approach for dapp functionality.
=> fix: make signer send and allow jwk to be cloned

kubo-rpc-server.patch, kubo-rpc-server/.openapi-generator/FILES, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/docs/SwarmPeersPost200Response.md, kubo-rpc-server/docs/SwarmPeersPost200ResponsePeersInner.md, kubo-rpc-server/docs/default_api.md, kubo-rpc-server/src/client/mod.rs, kubo-rpc-server/src/lib.rs, kubo-rpc-server/src/models.rs, kubo-rpc/kubo-rpc.yaml, kubo-rpc/src/http.rs
The change to openapi for kubo dropped the `Peers` key from the /swarm/peers endpoint. This fixes it.
=> fix: wrap returned peers in "Peers" key

beetle/iroh-bitswap/src/client/session.rs, kubo-rpc/src/lib.rs
The bitswap Session type had a cycle (via an Arc<SessionManager>) back to itself causing a stackoverflow when formatted via Debug. This removes the cycle.
=> fix: remove cycle in debug output

.github/workflows/rust.yml
With this change we now cache the registry via `Swatinem/rust-cache@v2` and we cache intermediate compilation steps via `mozilla-actions/sccache-action@v0.0.3`. Additionally we split the single `build` job into three parallel jobs, `check`, `test`, and `build`.  After a few tries I am seeing builds around 20m now.
=> chore: use sccache for better Rust caches

Cargo.lock, beetle/iroh-bitswap/src/client/peer_manager.rs, beetle/iroh-bitswap/src/client/peer_want_manager.rs, beetle/iroh-bitswap/src/lib.rs, kubo-rpc/Cargo.toml, kubo-rpc/src/lib.rs, one/Cargo.toml, p2p/src/node.rs
Prior to this change bitswap assumed it was the only behaviour asking the swarm to dial peers, as such when a dial failure occurred it marked the peer as failed and would not send want-haves to the peer.
However this behavior did not work well with the behavior to auto discover ceramic peers and dial them. When ceramic peers were discovered it was possible that they were already connected in which case the `DialFailedPrecondition` error would be reported causing bitswap to mark the peer as failed even though we have a valid connection open to the peer.
This change modifies the bitswap behavior to only modify peer state when a connection closed event is received instead of dial failures. A peer is not marked as good until a connection is established so marking a peer as failed when the …
=> fix: change bitswap dial behavior

one/src/sql.rs
We were seeing connection pool timeouts under heavy concurrent write load. I determined the sqlite prefers to have a single active connection at a time and to queue the rest of the work in the `acquire` stage.
I tested this by running the daemon process with restricted resources, specifically 2 CPUs 1GB RAM and only 64 IOPS. I then wrote 5K unique blocks that were each ~512 bytes. The concurrency was 2K for writing blocks.
With default settings on the order of 1% of writes would fail with repeated tests. With changing the settings to a single active connection the failure rate was 0% with repeated tests.
I also tests with even fewer IOPS to see higher failure rates and confirmed that 1 active connection performed best.
Finally I tested increasing the active connections to really high …
=> fix: optimize sqlx pool options

Cargo.lock, kubo-rpc/Cargo.toml, kubo-rpc/src/http.rs, kubo-rpc/src/id.rs
This change follows Kubo's implementation and is helpful for clients as then can simply iterate through the list of addrs when attempt to peer with them instead of having to construct the full mulitaddr themselves.
=> fix: append peer id to all listen addrs

Cargo.lock, kubo-rpc/Cargo.toml, kubo-rpc/src/http.rs, kubo-rpc/src/http/stream_drop.rs, kubo-rpc/src/lib.rs, kubo-rpc/src/pubsub.rs
Prior to this change the pubsub/ls endpoint would return the raw topic names when the should be base64url encoded names.
Additionally the subscription would remain even after the subscription connection had closed. This is now fixed.
=> fix: change pubsub/ls to return base64url encoded topics

Cargo.lock, kubo-rpc-server.patch, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/docs/default_api.md, kubo-rpc-server/examples/client/main.rs, kubo-rpc-server/examples/server/server.rs, kubo-rpc-server/src/client/mod.rs, kubo-rpc-server/src/lib.rs, kubo-rpc-server/src/server/mod.rs, kubo-rpc/Cargo.toml, kubo-rpc/kubo-rpc.yaml, kubo-rpc/src/http.rs
There is an undocumented `timeout` query parameter to the `block/get` Kubo RPC endpoint that the js-ceramic code relies on. This change adds an implementation of that argument.
TODO:
=> fix: add block get timeout

kubo-rpc-server.patch, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/docs/default_api.md, kubo-rpc-server/examples/client/main.rs, kubo-rpc-server/examples/server/server.rs, kubo-rpc-server/src/client/mod.rs, kubo-rpc-server/src/lib.rs, kubo-rpc-server/src/server/mod.rs, kubo-rpc/kubo-rpc.yaml, kubo-rpc/src/block.rs, kubo-rpc/src/http.rs, kubo-rpc/src/lib.rs
Adds another undocumented parameter to block/get. Offline indicates the node should not ask the network for the block but instead only check its own store.
=> feat: add offline parameter to block/get

Dockerfile
Rust-builder uses only the latest tag now.
=> fix: use rust-builder latest

one/src/main.rs, one/src/network.rs, p2p/src/behaviour.rs, p2p/src/node.rs
We are seeing issue related to Kademlia and seem to be connected to Ceramic peer discovery. As this feature is not needed currently, its being removed to eliminate any compounding variables. Once its needed (when we remove gossipsub) it can be reintroduced and fully tested against our established baseline.
=> fix: remove Ceramic peer discovery

Cargo.lock, Cargo.toml, beetle/iroh-metrics/src/config.rs, beetle/iroh-metrics/src/lib.rs, one/src/main.rs
There are now three log format options.
* Single Line - Uses colors and everything is on a single line
* Multi Line - Uses colors and multiple lines to display more context
* JSON - Does not use colors and formats add structures as JSON on a single line.
This change also makes the default log level INFO.
Fixes WS1-1292
=> feat: add explicit log format CLI option

one/src/lib.rs
CERAMIC_ONE_SWARM_ADDRESSES default_values port 4001
=> feat: default swarm port

kubo-rpc/src/http/metrics.rs, kubo-rpc/src/ipfs_metrics.rs, kubo-rpc/src/lib.rs, one/src/lib.rs, one/src/network.rs
Now we can separately see calls counts and durations to Ipfs operations directly. Instead of only the toplevel Kubo RPC API requests.
=> feat: add ipfs metrics

one/src/lib.rs, p2p/src/behaviour.rs, p2p/src/config.rs
Expose basic kademlia config. I anticipate we can remove many of these in the future but we need to be able to change them quickly in order to test them.
=> feat: expose basic kademlia config

one/src/lib.rs, p2p/src/node.rs
Prior to this change autonat would always be enabled. Now it can be disabled in cases where NAT is not being used.
Additionally previously an unbounded number of probes would be running concurrently for all observed addresses. When an dynamic outbound NAT is used this results in many probes. Now we limit to one active probe at a time and also track failed external address so we do not repeatedly attempt to probe them.
=> feat: add control over autonat

p2p/src/behaviour.rs
I have learned that behaviours are called in order and therefore its best practice to place the behaviours that deny connections first in the list. See https://github.com/libp2p/rust-libp2p/pull/4777#discussion_r1391833734
=> fix: check limits first before other behaviours

metrics/src/macros.rs, p2p/src/metrics.rs, p2p/src/node.rs, p2p/src/publisher.rs
This change makes the Publisher logic run in its own task. This is to relieve CPU pressure from the swarm task.
=> fix: run publisher in its own task

p2p/src/node.rs, p2p/src/publisher.rs
Instead of sending all 1000 keys in a batch in one iteration of the swarm loop send one. This way the swarm can continue to process other concurrent work. Tests show this is still fast enough to send out all publish queries within a few seconds.
=> fix: trickle publisher keys to swarm

one/src/lib.rs, p2p/src/behaviour.rs, p2p/src/behaviour/ceramic_peer_manager.rs, p2p/src/behaviour/event.rs, p2p/src/config.rs, p2p/src/node.rs
Prior to the peer_manager connecting to bootstrap peers we relied on kademlia to connect to them. Now not only is it not necessary but the peer_manager applies an appropriate backoff for redials where kademlia does not. There should be no change in external behavior except that we no longer spam dials to disconnected bootstrap peers.
Now the peer_manager (renamed to ceramic_peer_manager) can report of a peer id is a ceramic peer. If we connect to a ceramic peer we add it to the kademlia routing table regardless of its reported protocols. This is because we discovered that peers sometimes do not report they support the kademlia protocol.
We (@smrz2001  and I ) decided that renaming bootstrap peers to ceramic peers was best because it communicates the role the peers play as opposed to what …
=> fix: do not use bootstrap list with kademlia

p2p/src/metrics.rs, p2p/src/node.rs, p2p/src/publisher.rs
Prior to this change the publisher attempted to estimate and amortize the DHT publish load over the entire interval. Now we use a simpler AIMD method and then publish batches without any delay. Additionally no estimate metrics are computed instead two simple metrics of how many remaining records need to be published and the amount of time before the deadline. Now operationally you can estimate the lag, buts the code itself is simpler.
Additionally logic was added to not start publishing until kademlia has been bootstrapped.
Finally the dynamic batch size has been capped to min and max sizes to ensure we always make at least some progress and we have a upper bound (for the internal channel) on how large a batch will get.
=> fix: simplify the publisher

Cargo.lock, Cargo.toml, beetle/iroh-bitswap/Cargo.toml, beetle/iroh-bitswap/src/handler.rs, beetle/iroh-bitswap/src/lib.rs, one/Cargo.toml, one/src/lib.rs, one/src/network.rs, p2p/Cargo.toml, p2p/src/behaviour.rs, p2p/src/behaviour/ceramic_peer_manager.rs, p2p/src/node.rs, p2p/src/providers.rs, p2p/src/publisher.rs, p2p/src/rpc.rs, p2p/src/swarm.rs, recon/Cargo.toml, recon/src/libp2p.rs, recon/src/libp2p/handler.rs, recon/src/libp2p/tests.rs
Libp2p has three major features we want:
1. Stable support for QUIC
2. Full tracing support
3. Uses prometheus_client 0.22, this enables use to use tokio-metrics
In order to upgrade we needed to address the follow major breaking changes:
* KeepAlive is now a boolean signal (bitswap keep alive logic is now much simpler)
* Supported Protocols are only known per connection, we now hard code the list for diagnostic reasons
There are a few other minor breaking changes but did not affect our code much.
Closes WS1-1291
Closes WS1-1345
=> fix: upgrade to libp2p 0.53

.github/workflows/deploy-image.yml, .github/workflows/publish.yml
This PR allows manual deployments to any of our 4 k8s envs. The CD workflow on pushes to main has been minimally updated so we can test CD and will need to be expanded once we have the additional branch and pre/release workflow updates.
=> fix: update deploy workflows for k8s

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Check limits first before other behaviours (#183)
- Panic with divide by zero duration math (#184)
- Fix JSON log format errors (#185)
- Update comment to pass clippy (#189)
- Run publisher in its own task (#188)
- Trickle publisher keys to swarm (#191)
- Use AIMD for publisher batch size (#195)
- Do not use bootstrap list with kademlia (#199)
- Simplify the publisher (#200)
- Always collect metrics (#202)
- Typo (#203)
- Upgrade to libp2p 0.53 (#205)
- Clippy accessing first element with first (#212)
- Update deploy workflows for k8s (#216)
- Rename workflows (#223)
- Continously publish provider records (#175)
- Add publisher batch metrics (#187)
- Add config for republish_max_concurrent (#192)
- Add peering support (#194)
- Add tokio metrics (#206)
- Merge migration script with …
=> chore: version v0.10.0

.github/workflows/cd-to-infra.yml, .github/workflows/publish-prerelease.yml, .github/workflows/publish-release.yml, ci-scripts/release_pr.sh
Based on @samika98's [PR](https://github.com/ceramicnetwork/rust-ceramic/pull/219) with some minor changes. More comments than actual code changes 😄 
We've retained the release PR process to bump the TOML version. This ensures that a release is not only a manual action but one that _requires approval_ from at least one other team member.
A workflow that could create a release directly would also have been fine but requiring approval seems like a better approach in principle.
The process for creating (pre)releases and their relationship to deployments is as follows:
- Create release PR bumping TOML version (e.g. v0.10.0).
- Merge of PR creates a GH pre-release with tag v0.10.0.
- This generates the `published` trigger that causes a deployment to `tnet`.
- Repeat as many times as needed to …
=> feat: updated release workflow

api/src/server.rs, core/src/lib.rs, core/src/sql.rs, p2p/src/node.rs, recon/src/client.rs, recon/src/metrics.rs, recon/src/protocol.rs, recon/src/recon.rs, recon/src/recon/btreestore.rs, recon/src/recon/sqlitestore.rs, recon/src/recon/store_metrics.rs, recon/src/recon/tests.rs
Linear WS1-1432.
Before making any changes, I was seeing about 400/100 rps keys added/synced. After these changes, we're able to push the incoming over 1k, and a steady workload targeting 300 completed with ~310/240 keys exchanged/sec. 
**Changes**: 
- I moved the recon values into their own table: `recon_value`. This doesn't have any real benefit up front, but as the table grows it will help. Eventually, a single table will pay during reads as scans will load a lot more data. The value is about 10x bigger and will explode row sizes: a key is ~80 bytes and the value is ~1KB. The initial change moved writes up and syncs down: 450/65.
- In a POC, I left things in a single table and hit around 800/100 rps just changing the events_post insert to use a single statement. I expect we could push …
=> feat: Modify recon storage tables, trait and sqlite config to improve throughput

api/src/server.rs, core/src/event_id.rs, core/src/interest.rs, p2p/src/node.rs, recon/src/client.rs, recon/src/metrics.rs, recon/src/protocol.rs, recon/src/recon.rs, recon/src/recon/btreestore.rs, recon/src/recon/parser.lalrpop, recon/src/recon/sqlitestore.rs, recon/src/recon/store_metrics.rs, recon/src/recon/tests.rs
This change updates the Recon protocol to check for any missing values when a synchronized range of keys is discovered. This way as nodes are synchronized they ensure they also have all values for their known keys.
TODO
=> feat: synchronize value for synchronized ranges

event/src/args.rs, event/src/deterministic_init_event.rs, event/src/event.rs
Adds support for documents that have a unique header but no data. Additionally reduces usage of lifetimes as they only add complexity.
=> feat: support for set type documents

api/src/server.rs, core/src/event_id.rs, core/src/interest.rs, core/src/lib.rs, core/src/range.rs, recon/src/recon.rs, store/src/sqlite/interest.rs, store/src/sqlite/model.rs
This changes the recon::Key trait to use TryFrom<Vec<u8>> instead of simply From<_> in order to allow for validation of the bytes. Now it _should_ be impossible to construct either an Interest or an EventId that is not valid. Remembering that a fencepost is considered valid.
=> fix: use try_from on recon keys

store/src/sqlite/model.rs
I returned 0 as the default rowid, which is great the _first_ time but a bug when there actually had been data previously. Now we use the previous rowid (i.e. resume token) if nothing was found. We don't want to go back to the beginning when there isn't anything new as the client polls for this information currently and this is expected to happen frequently.
We could query the max(rowid) from the database to guarantee we're at the current resume token, if for some reason the client sent us 10000 but it's actually 1000. I don't think there's really a point to do that, as we trust our clients and there's no reason that should happen (famous last words?). I can change this if anyone disagrees.
=> fix: resume token should return previous (not 0) when nothing found

store/src/metrics.rs
The store/query metrics are now under their own subregistry (ceramic_store) rather than using recon. This makes sense based on the code layout, but was put off as it requires updating the performance tests as they look at this metric.
=> fix: store metrics under own registry (not recon)

one/src/lib.rs
Now that we have broken compatibility with Kubo APIs the only purpose of ceramic-one is to run Recon. As such we should enable it by default as the binary doesn't do anything meaningful with it disabled.
=> feat: enable recon by default

api-server/.openapi-generator/FILES, api-server/README.md, api-server/api/openapi.yaml, api-server/docs/EventsPostRequest.md, api-server/docs/default_api.md, api-server/examples/server/server.rs, api-server/src/client/mod.rs, api-server/src/lib.rs, api-server/src/models.rs, api-server/src/server/mod.rs, api/ceramic.yaml, api/src/metrics/api.rs, api/src/server.rs
I renamed the fields on the Event schema to save bytes but only supported that in responses to avoid breaking changes, but there was a path forward to support both for inputs without breaking anything. We do this for now, and can update callers to `id/data` instead of `event_id/event_data` and simplify the input validation at that time. 
We prefer `id/data` over `event_id/event_data` and don't allow mixing. I was going to allow either `id` field and either `data` field, but this ensures people are using either style correctly and completely, rather than a hybrid.
The implementation is ugly, as using `oneOf` schema generation doesn't work quite right. It generated 4 required fields on one struct, rather than an enum with 2 variants with 2 required fields each. So instead I crate a new type …
=> feat: support new id/data event payload for event creation (POST /events)

.github/workflows/create-release-pr.yml
Use the existing `GH_TOKEN_PAT` for release creation as the GITHUB_TOKEN doesn't initiate actions.
Reference:
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs.
=> fix: use PAT for create-release-pr workflow

api-server/.openapi-generator/FILES, api-server/README.md, api-server/api/openapi.yaml, api-server/docs/EventsGet.md, api-server/docs/default_api.md, api-server/examples/client/main.rs, api-server/examples/server/server.rs, api-server/src/client/mod.rs, api-server/src/lib.rs, api-server/src/models.rs, api-server/src/server/mod.rs, api/ceramic.yaml, api/src/metrics/api.rs, api/src/server.rs
`GET /events/{sort_key}/{sort_value}?controller={did}&streamId={sId}&limit={int}&offset={int}`
Returns a response like
```json 
{
"events": [{"id": "", "data": ""}],
"resumeOffset": "int",
"isComplete": "bool"
}
```
I considered reusing the EventFeed response, but used something different to make the "resume" semantics clear. Feed supports the token in all cases, whereas the `resumeOffset` is only "valid" (that is, useful) with the same parameters. It also may not be a permanent endpoint, or we may want to evolve it separately, so they only share the Event body currently.
I made some small refactors to the server.rs code to build the response objects in one place (that is, consolidate the encoding), and to build the start/end range as a function so we can share between this and the …
=> feat: create GET endpoint to return events for an interest range

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Use PAT for create-release-pr workflow (#275)
- Honor PENDING_RANGES_LIMIT for initial ranges (#271)
- Create GET endpoint to return events for an interest range (#276)
=> chore: version v0.12.0

.github/workflows/pr-semantic-message.yml
Instead of linting all commits we will now lint the commit message if it is the only commit in the PR otherwise we will lint the PR title.
=> chore: only lint single commit or PR title

ci-scripts/schedule_k8s_deploy.sh, ci-scripts/schedule_tests.sh
Using the new `labels` field enabled via [this](https://github.com/3box/pipeline-tools/pull/58) PR.
=> fix: pass job labels to designate notification channels

recon/src/libp2p/handler.rs
Prior to this change we would emit a warning every time we connected to a peer that did not speak the recon protocol. As we connect to many peers for the DHT that do not speak Recon the warn was triggered a lot. We do not need the warn as its not generally helpful debugging information.
=> fix: remove loud warn from Recon

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Add rust-ceramic clay bootstrap nodes (#288)
- Pass job labels to designate notification channels (#281)
- Remove loud warn from Recon (#287)
- Delete subscribe endpoint (#277)
- Only lint single commit or PR title (#279)
- Remove support for old event payload during creation (#272)
=> chore: version v0.13.0

api-server/.openapi-generator/FILES, api-server/README.md, api-server/api/openapi.yaml, api-server/docs/ErrorResponse.md, api-server/docs/default_api.md, api-server/src/client/mod.rs, api-server/src/lib.rs, api-server/src/models.rs, api-server/src/server/mod.rs, api/ceramic.yaml, api/src/server.rs
Addresses WS1-1518.
All Recon API errors are now of the format `{"message": "some text"}` instead of just a string. In order to make sure I didn't miss anything, I moved all the logic inside the server struct impl, rather than the trait. This allows using `or_else(|err| Ok(resp::InternalServerError(err))`. We don't return the swagger ApiError struct in any cases. The diff looks a bit intimidating, but it's pretty much just moving some things around. The responses change from `<_,ApiError>` to `<_, ErrorResponse>` and the trait impl maps them.
=> feat: use standard error response body for API 

api-server/.openapi-generator/FILES, api-server/README.md, api-server/api/openapi.yaml, api-server/docs/BadRequestResponse.md, api-server/docs/Interest.md, api-server/docs/default_api.md, api-server/examples/client/main.rs, api-server/examples/server/server.rs, api-server/src/client/mod.rs, api-server/src/lib.rs, api-server/src/models.rs, api-server/src/server/mod.rs, api/ceramic.yaml, api/src/metrics/api.rs, api/src/server.rs
Linear WS1-1519
Creates a new `POST /interests` route that takes a post body. Shares the implementation with the existing `/interests/{separator}/{model}` route. I didn't modify the existing route as there is no way to remove the required path parameters. If we want that, I don't think we should include them in the payload body as required in the ticket. 
Two other things of note:
1. stream values are now required to be multibase encoded and we convert them to base36 before storing the interest.
2. I modified the all the existing routes to use a shared BadRequest object that matches the format of the error object i.e. `{"message": "string"}` body. 
Based on #284
=> feat: add POST interests route that accepts body instead of path/query parameters

api-server/README.md, api-server/api/openapi.yaml, api-server/docs/default_api.md, api-server/examples/client/main.rs, api-server/examples/server/server.rs, api-server/src/client/mod.rs, api-server/src/lib.rs, api-server/src/server/mod.rs, api/ceramic.yaml, api/src/metrics/api.rs, api/src/server.rs
Linear ticket WS1-1522. 
Created a new GET /experimental/events/{sep}/{model} route to query events by an interest filter. The old route still exists (marked deprecated) until the tests are updated and then it can be deleted.
Targets #285 which targets #284
=> feat: move GET events by interest route under experimental

README.md
Minor doc update for shiny new computer setups wanting to compile using `cargo run`.
=> docs: added explicit deps to build steps

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Standard 500 error response body (ws1-1518) (#284)
- Add POST interests route that accepts body instead of path/query parameters (#285)
- Move GET events by interest route under experimental (#286)
- Moved api tests to a separate file (#268)
- Added explicit deps to build steps (#291)
=> chore: version v0.14.0

.github/workflows/cd-to-infra.yml, .github/workflows/rust-build-and-test.yml, ci-scripts/publish.sh
Only tag the workflow docker image with "latest" when it's a merge to main.
Currently we're getting branches tagged with latest.
=> fix: use TAG_LATEST

beetle/iroh-bitswap/src/peer_task_queue/peer_tracker.rs, p2p/src/node.rs, recon/src/client.rs, recon/src/recon.rs, recon/src/recon/btreestore.rs, recon/src/recon/tests.rs, recon/src/tests.rs, store/src/metrics.rs, store/src/sql/event.rs, store/src/sql/interest.rs
We don't need the store to be mutable and this was also implemented in the RedTree branch, but it hasn't been pulled out separately yet (https://github.com/ceramicnetwork/rust-ceramic/pull/280). Helps with the `Box<dyn>` changes to determine the database at runtime.
=> chore: remove mut from store traits

Cargo.lock, api/src/server.rs, api/src/tests.rs, beetle/iroh-bitswap/src/client.rs, beetle/iroh-bitswap/src/lib.rs, beetle/iroh-bitswap/src/server.rs, beetle/iroh-bitswap/src/server/blockstore_manager.rs, beetle/iroh-bitswap/src/server/decision.rs, kubo-rpc/src/lib.rs, one/src/events.rs, one/src/lib.rs, one/src/network.rs, p2p/src/behaviour.rs, p2p/src/node.rs, p2p/src/swarm.rs, recon/src/client.rs, recon/src/lib.rs, recon/src/recon.rs, recon/src/recon/btreestore.rs, recon/src/recon/tests.rs, store/Cargo.toml, store/src/lib.rs, store/src/metrics.rs, store/src/sql/event.rs, store/src/sql/interest.rs, store/src/sql/mod.rs, store/src/tests.rs
Adjusts types so that they may be used from a dynamic context, which allows other database implementations to be provided. Additionally types no longer require clone, but instead use arc as needed for clone.
=> chore: adjust types to allow dynamic usage

Cargo.lock, recon/Cargo.toml, recon/src/libp2p.rs, recon/src/libp2p/handler.rs, recon/src/metrics.rs, recon/src/protocol.rs, recon/src/recon/tests.rs
We have a "transient" error type (for now) to indicate that we had an internal failure during sync and should retry, rather than mark the peer as failed, which terminates the conversation.
This also incorporates the sync_id changes in #304.
=> feat: don't mark peers failed when we error during sync

p2p/src/behaviour.rs, p2p/src/node.rs, p2p/src/swarm.rs, recon/src/libp2p.rs
Remove uses of std::thread and ensure the p2p poller is appropriately tied to a waker.
=> chore: don't hang the executor

.github/workflows/cd-to-infra.yml, Makefile, ci-scripts/publish.sh
This change builds two images a release and debug build. The same tags for the debug build are used as the release build with the addition of a `-debug` suffix. This also changes the deploy code to deploy the debug builds to infra. We can revert that change or parameterize it later.
=> chore: add debug image builds

p2p/src/node.rs, p2p/src/swarm.rs
Use a tokio task instead of spawning a `std::thread`. This should help with starvation/resource utilization as the runtime is aware and able to schedule it. There is more work to be done refactoring/adjusting/simplifying the libp2p code, but this is a small change to start. I actually removed it from #307 because I thought it caused errors, but misunderstood the test failures as a simply the single threaded runtime 🤦.
Decided to drop the recon ConnectionHandler waker implementation I added as it didn't seem to make much difference, and after review yesterday, it seems like the behavior will poll its connections. Again, this may be adjusted as part of fixing the "one side errors and the other side waits forever" issue, and the broader changes we've been discussing.
=> chore: spawn tokio task instead of std thread 

Dockerfile, api/Cargo.toml, api/src/server.rs
jemalloc-pprof is only supported on linux (i.e. uses `dl_iterate_phdr` from libc) and doesn't compile on osx. I added a simple config check, not sure if this could/should be more sophisticated. It seems that this is likely supported on BSD and a handful of other platforms but I didn't investigate.
=> fix: rust-jemalloc-pprof is only supported on linux

Cargo.lock, Cargo.toml, metrics/Cargo.toml, metrics/src/lib.rs
While investigating a memory leak in ceramic-one, we discovered that it was in tokio-console. I updated the telemetry dependencies as well thinking it might have been the cause before we identified the console.
=> chore: update open telemetry and tokio-console dependencies

Cargo.lock, one/src/events.rs, p2p/src/node.rs, recon/Cargo.toml, recon/src/client.rs, recon/src/error.rs, recon/src/lib.rs, recon/src/libp2p/tests.rs, recon/src/protocol.rs, recon/src/recon.rs, recon/src/recon/btreestore.rs, recon/src/recon/tests.rs, store/Cargo.toml, store/src/error.rs, store/src/lib.rs, store/src/metrics.rs, store/src/sql/entities/event.rs, store/src/sql/entities/mod.rs, store/src/sql/event.rs, store/src/sql/interest.rs, store/src/sql/sqlite.rs
This adds a Error enum to the store and recon crates that allows for some error handling/decision making, rather than propagating all errors up as opaque failures. This doesn't actually handle or retry errors yet, just provides the types to do so. This is targeting #320 as it was originally on the postgres branch, and it simplified conflicts/rework (and I'm hoping that branch isn't too contentious, even though the commit is large).
=> chore: add variants for error handling

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Validate time events (#289)
- Add workflow for custom images
- Migrations with new table format to de-dup blocks and support out of order delivery (#292)
- Don't mark peers failed when we error during sync (#300)
- Jemalloc (#319)
- Store bench (#303)
- Disable mdns,bitswap,kad,relay,dcutr protocols (#323)
- Use TAG_LATEST (#294)
- Set the js-ceramic image when scheduling k8 deploy (#298)
- Gh workflow syntax
- Cd-to-infra workflow quote fix (#314)
- Tokio vs std thread is okay (#318)
- Rust-jemalloc-pprof is only supported on linux (#321)
- Remove mut from store traits (#305)
- Adjust types to allow dynamic usage (#306)
- Don't hang the executor (#307)
- Recon libp2p e2e tests (#310)
- Add debug image builds (#311)
- Update debug tags when not releasing (#313)
- Fix docker build for …
=> chore: version v0.15.0

api-server/README.md, api-server/api/openapi.yaml, api-server/docs/Event.md, api-server/src/models.rs, api/src/server/event.rs, event/src/unvalidated.rs
Parses unsigned init events and can construct an EventId from its car file.
=> fix: parse unsigned init events

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Remove deprecated http API for getting events for a single interest (#332)
- Changes to improve sync and ingest performance (#324)
- Fix clippy (#334)
- Update deps cid, multihash, and ipld (#309)
- Add bad request response to get events API (#329)
- Run build/test/check CI on all PRs (#333)
=> chore: version v0.16.0

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Update events GET API to return event CID instead of EventID
- Return event root cid instead of EventID from feed
- Update experimental API for getting a range of events to return event root CID, not EventID (#337)
- Simplify event id
- Add serde methods for Events
- Make event creation endpoint infer EventID from event CAR file data (#341)
- Remove id argument from events POST endpoint (#347)
- Parse unsigned init events
- Handle data events with unsigned init events (#348)
- Rename payload -> init_payload
- SQL queries for event blocks dont need order_key
- Update comment for Event type in API (#338)
- Make gen-api-server
=> chore: version v0.17.0

Cargo.lock, recon/Cargo.toml, recon/src/libp2p/handler.rs, recon/src/libp2p/protocol.rs, recon/src/libp2p/tests.rs, recon/src/metrics.rs, recon/src/protocol.rs, recon/src/recon/tests.rs
If two nodes each had 2K+ events that the other node did not have it was possible for the protocol to deadlock as both nodes tried to write those events without read the values from the other node.
The fix was accomplished by splitting the protocol into two loops, a read loop and a write loop. They communicate with each other using message passing. The code now has both a clean separation of concerns as well as the behavior that we concurrently read and write from the network so we do not enter a state where we are exclusively writing to the network.
=> fix: recon protocol hang with large diffs

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Adjust recon bounds to be lower inclusive and always store value
- Use builder pattern to create unvalidated and validated events
- Update event types and builder APIs to prevent building events that dont align with the protocol spec (#357)
- In order delivery of ceramic events (#344)
- Remove first/last from recon::Store trait
- Lower correctness test network ttl
- Move network ttl to hermetic driver command
- Tests
- Recon protocol hang with large diffs (#356)
- Make recon value required
- Remove value parsing from recon tests
- Optimize remote missing edge cases
- Remove keys_with_missing_values from all traits
- Add service crate (#354)
- Address review feedback
- PR review comments (#346)
- Clippy
- Review and test fixes
- Unused deps
- Make event struct fields private (#359)
=> chore: version v0.19.0

event/src/unvalidated/builder.rs, event/src/unvalidated/payload/init.rs
The "context" field was added to support OrbisDB, see [forum.ceramic.network/t/asking-for-support-of-the-context-field-in-the-metadata-object-for-streams/1425](https://forum.ceramic.network/t/asking-for-support-of-the-context-field-in-the-metadata-object-for-streams/1425) for more info.
=> fix: Add context to init event header

service/src/event/ordering_task.rs, service/src/tests/ordering.rs
Before, an event might be left hanging undelivered until an additional event came in for the stream. Now we check undelivered events for a stream any time something is added to it (whether we expect it to unblock something or not).
Originally, I naively used interval loops to check all pending streams, and checked all events in cases that were unnecessary. So I decided to be more clever and only check a stream when something impacted it directly, and remove the silly interval looping that was checking things we _knew_ we couldn't process. Only I overlooked the fact that I removed checking incoming events when they had a `prev` *at all* until a write came in that we expected might unblock something. This left an entire set of events (i.e. the SECOND one) unchecked, and without the interval …
=> fix: events incorrectly left undelivered

api/src/server.rs, one/src/lib.rs, recon/src/libp2p.rs, recon/src/protocol.rs, recon/src/recon/tests.rs
It was possible for the conversation to stall if the peers shared no interests. Now the initiator will send a finished message immediately and the conversation will end, allowing a future iteration to discover new overlapping interests.
=> fix: recon protocol stall with no shared interests

api/src/server/event.rs, event/src/unvalidated/event.rs, event/src/unvalidated/signed.rs
There should be no functional changes here, just code refactoring.
This PR splits the `event_id_from_car` function into two phases: first parse the CAR data into an Event struct, solely based on the data in the car without any reliance on the blockstore.  Then, given the Event struct and access to the blockstore, get the EventID.  This is setting the groundwork to be able to add the code that re-serializes the Event struct back into a CAR file to compare the bytes and ensure that no extra fields are present.
=> chore: Deserialize CAR into Event before extracting EventID

api/src/server/event.rs, event/src/unvalidated/payload/init.rs
builds on https://github.com/ceramicnetwork/rust-ceramic/pull/362.
There was no easy way to unit test this change, but I have a PR ready for a test in ceramic-tests that will exercise this: https://github.com/3box/ceramic-tests/pull/129
=> feat: disallow events with unexpected fields via the http api

one/src/http.rs
The correctness tests call this path a lot and it's exploding prom metrics. This should be the only existing route that was missed, the others have been accounted for or use query parameters which are removed.
=> chore: fix prom cardinality for test path

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Get feed highwater mark to start from "now" (#370)
- Fix prom cardinality for test path (#372)
=> chore: version v0.22.0

Cargo.lock, Cargo.toml, api/Cargo.toml, api/src/server/event.rs, api/src/tests.rs, event/src/unvalidated/builder.rs, kubo-rpc/Cargo.toml, kubo-rpc/src/http.rs, one/Cargo.toml, one/src/events.rs, service/Cargo.toml, service/src/event/ordering_task.rs, service/src/tests/event.rs, service/src/tests/interest.rs, service/src/tests/ordering.rs, store/Cargo.toml, store/src/sql/test.rs
Running with tokio-console on could cause subscribers to register and conflict on the port so now we don't init tracing manually and instead rely on `test-log`. `tracing_test` is only to assert log statements, not get debug tests like we want so it was replaced.
Requires running with `--nocapture` i.e. `RUST_LOG=info cargo test -- --nocapture`
=> chore: replace tracing_test with test-log

service/src/event/ordering_task.rs, service/src/event/service.rs, service/src/event/store.rs, service/src/tests/mod.rs, service/src/tests/ordering.rs, store/src/lib.rs, store/src/metrics.rs, store/src/sql/access/event.rs, store/src/sql/access/mod.rs, store/src/sql/entities/event.rs, store/src/sql/entities/event_block.rs, store/src/sql/entities/hash.rs, store/src/sql/entities/mod.rs, store/src/sql/entities/utils.rs, store/src/sql/mod.rs, store/src/sql/query.rs, store/src/sql/test.rs
Use deliverable instead of delivered language. Fixes the possibility of changing the delivered integer value after is has been set. Modifies the insert events response to include some more information. This is probably not strictly necessary, but it does make it easier to map things back after they have been reordered in the case of recon that only cares about original order.
=> refactor: modify store API and rename some things 

api/src/lib.rs, api/src/server.rs, api/src/tests.rs, service/src/event/service.rs, service/src/event/store.rs, store/src/metrics.rs
Previously, an API insert batch with a single event with invalid ordering could fail the entire set. It's still possible to "over fail" if something goes wrong somewhere (talking to the database or one of the events fails to parse), however both of those seem acceptable as the events are all parsed before being given to us so that should never happen. I'd like to change the signature to take an ceramic_event type in a follow up, but this is some progress in that direction. It builds on #390.
=> fix: api batch with one invalid event could fail all

metrics/src/core.rs, one/src/http_metrics.rs, store/src/metrics.rs
This will break existing dashboards (of which there are few well defined examples I believe), but it will make building new ones much easier as all metrics will start with `ceramic_one_` now. This also renamed `http_api_http_api` to `ceramic_one_http_api_info` and `ceramic_store_store_query_durations` will now be `ceramic_one_store_query_durations`, and other store metrics will be under `ceramic_one_store`.
The existing tokio, recon, libp2p, bitswap subregistries are all under ceramic_one now:
=> chore: rename prometheus registry and metrics for better consistency

service/src/event/migration.rs, service/src/event/mod.rs, service/src/event/order_events.rs, service/src/event/ordering_task.rs, service/src/event/service.rs, service/src/tests/mod.rs, service/src/tests/ordering.rs, store/Cargo.toml, store/benches/sqlite_store.rs, store/src/sql/access/event.rs, store/src/sql/entities/event.rs, store/src/sql/query.rs, store/src/sql/test.rs
Address AES-83 and replaces part of #375 and incorporates a lot of the feedback from that one. Depends on #390.
This changes the initial "deliver all undelivered events" process to happen when creating a `CeramicEventService`, which means it could take a while, and will block (or prevent if it fails) the server from starting rather than happen in the background.
There are new/better tests. Some where deleted/replaced that were specific to the IOD implementation details and the higher API is now tested exclusively. The general premise is to send recon events to the task, and it will track them in memory if they need history. Delivered events will be be stored if we have the stream in memory, and will trigger a review of the stream if they unblock something we have. If we don't have the …
=> fix: IOD long streams could remain undelivered

event/src/unvalidated/event.rs, event/src/unvalidated/payload/init.rs, metrics/src/lib.rs, one/src/migrations.rs, service/src/event/migration.rs, service/src/tests/migration.rs
There were two edge cases not covered with the time event migration code:
1. The time event previous may be either a signed or unsigned event.
2. The witness nodes may contain null entries.
Additionally fixes a bug with initializing tracing for the migration CLI cmd and removes resulting dead code.
=> fix: address edge cases in from-ipfs time events

one/src/lib.rs
If you ran `ceramic-one daemon` the process could fail to start with an unhelpful message `Error: Application error encountered: (code: 14) unable to open database file`. Now, we create the directory (and all parents) before starting if necessary.
Fixes [AES-196](https://linear.app/3boxlabs/issue/AES-196/ceramic-daemon-doesnt-create-store-directory-and-fails-to-start).
=> fix: make sure the store directory exists and create it if needed

recon/src/libp2p/tests.rs, recon/src/recon.rs, recon/src/recon/btreestore.rs, service/src/event/migration.rs, service/src/event/order_events.rs, service/src/event/ordering_task.rs, service/src/event/service.rs, service/src/event/store.rs, service/src/interest/store.rs, store/src/metrics.rs, store/src/sql/access/event.rs, store/src/sql/test.rs
This addresses some feedback from #387. 
The `recon::Store` trait takes an explicit lifetime instead of elided because that could cause confusing issues (and in the changes to test with loom that got delayed we needed it #312). Mostly small clean up, other than changing the store insert_many function to take an `Iterator<Item = &'a EventInsertable>` and refactored some of the code in service to reduce allocations. 
~~I accidentally started from #398 so I'm currently targeting that but can rebase to main.~~
=> refactor: use an Iterator for insert_many and other clean up

.github/workflows/publish-prerelease.yml, .github/workflows/update-homebrew.yml, README.md, ci-scripts/package.sh
This PR adds support for easier installation of Ceramic on Macos through homebrew. When a new release is made, the [homebrew-tap](https://github.com/ceramicnetwork/homebrew-tap) repo is updated to point to the new version.
Not sure what the best way to test the CI workflow without breaking anything. Ideally this isn't merged until we've validated it works.
=> chore: homebrew support

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- IOD long streams could remain undelivered (#387)
- Address edge cases in from-ipfs time events (#395)
- Make sure the store directory exists and create it if needed (#401)
- Default missing sep to model (#404)
- Update correctness test selector (#406)
- Use event service rather than store to enforce deliverability/or… (#403)
- Homebrew support (#412)
- Update homebrew workflow (#413)
- Use pat for homebrew workflow (#415)
- Use an Iterator for insert_many and other clean up (#399)
- Mzk/readme installation (#397)
- Homebrew support (#407)
=> chore: version v0.26.0

ci-scripts/schedule_k8s_deploy.sh, ci-scripts/schedule_tests.sh
Also fixes a typo in the deployment script where the `js-ceramic` image for the env was being set.
=> fix: schedule post-deployment tests 15 min after deployment

Makefile, README.md, kubo-rpc/src/http.rs, one/src/lib.rs, one/src/main.rs, one/src/metrics.rs, p2p/src/node.rs
As we no longer provide a compatible IPFS server, we are changing the default ports we use from 4001 (swarm) and 5001 (rpc) to 4101 (swarm) and 5101 (rpc). This will avoid any conflicts with people running a vanilla IPFS server on their machine. I also added some better logging around errors binding addresses so you'll get something like the following, instead of something like: `Address already in use (os error 48)`.
```
❯ RUST_BACKTRACE=1 RUST_LOG=info,ceramic_store=debug ./target/debug/ceramic-one daemon --network local --local-network-id 0 --store-dir ./local-data
Connected to sqlite database: ./local-data/db.sqlite3
2024-07-01T19:58:09.317175Z  INFO ceramic_one: service__name: "ceramic-one", version: "0.25.0", build: "git:6acf4a09-modified", instance_id: "omniscient-volleyball", …
```
=> feat: change default ports used for swarm and rpc endpoint

one/src/lib.rs, p2p/src/node.rs, service/src/event/migration.rs, service/src/event/mod.rs, service/src/event/service.rs, service/src/event/store.rs, service/src/tests/event.rs, service/src/tests/migration.rs, service/src/tests/ordering.rs
You can skip ordering all the events in database on startup with a flag now (for use in the migration code). We also defer ordering all time events outside of the current batch until server startup. This reduces the memory pressure as we have to track everything while migrating it, and then duplicate quite a bit until it's found, which we can instead do successfully at the next start up. We still try to order the current batch as best we can so if an init and time event are in the same batch of 1000, they will be updated.
=> refactor: allow skipping ordering all events on start up and skip tracking during migration

one/src/lib.rs, one/src/migrations.rs, service/src/event/migration.rs, service/src/event/mod.rs, service/src/event/service.rs, service/src/lib.rs, service/src/tests/migration.rs
The migrations logic now does not need to read all blocks CIDs into memory.
This has a slight draw back from the previous code in that if a block was mislabeled on disk we would have still found it. Now we will not be able to find that block, however this is not expected to happen.
=> fix: optimize migrations logic for less memory

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Add explicit checking for tile documents for specific errors (#417)
- Add log-format option to migrations command (#420)
- Change default ports used for swarm and rpc endpoint (#411)
- Make private key dir configurable (#426)
- Add new mainnet and tnet bootstrap peers (#428)
- Update homebrew-tap push token (#418)
- Schedule post-deployment tests 15 min after deployment (#419)
- Optimize migrations logic for less memory (#424)
- Allow skipping ordering all events on start up and skip tracking during migration (#423)
- Add cargo testing docs (#394)
=> chore: version v0.27.0

Cargo.lock, one/Cargo.toml, one/src/lib.rs, one/src/migrations.rs
BREAKING CHANGE: Both the store and p2p key dirs now default to the current working directory instead of the home/.ceramic-one directory.
Generally this makes it less error prone when running multiple daemon on a single host as the naturally isolate from each other using their working directory. Running multiple daemons locally is a common task in order to experiment with the p2p nature of ceramic-one.
This is a breaking change. If you previously relied on the home directory default you must now explicitly pass in the home directory like so:
ceramic-one daemon -s ~/.ceramic-one -p ~/.ceramic-one
=> feat: change default dir to current directory

.github/workflows/publish-prerelease.yml, .github/workflows/update-homebrew.yml, README.md, ci-scripts/package.sh
This PR updates the pre-release process to also package binaries for linux. This will be helpful when creating an AUR package for arch linux.
Note: macos archives will change extension from `.tar.gz` to `.bin.tar.gz`, so we will likely need to update the archive names to include `.bin` on the most recent pre-release to not break the workflow.
Also changed the order of the README install instructions to Macos before Linux because I didn't want the Macos instructions to get lost under the *from source* instructions for Linux.
=> chore: release archive with linux binary

event/Cargo.toml, event/src/bytes.rs, event/src/unvalidated/event.rs, event/src/unvalidated/payload/data.rs, event/src/unvalidated/payload/mod.rs, event/src/unvalidated/signed/mod.rs
Adds Debug implementation for Event type and ensures CIDs are printed as strings instead of deconstruction of the CID struct
=> feat: add debug to all event types

api-server/README.md, api-server/api/openapi.yaml, api-server/docs/default_api.md, api-server/examples/client/main.rs, api-server/examples/server/server.rs, api-server/src/client/mod.rs, api-server/src/lib.rs, api-server/src/server/mod.rs, api/ceramic.yaml, api/src/server.rs, one/src/http.rs, one/src/lib.rs
Adds a cli flag `--cors-allow-origins` that defaults to `*` and supports a list. For example, running with `--cors-allow-origins "3box.io,localhost,https://ceramic.network"` and then going to https://ceramic.network and running `fetch('http://127.0.0.1:5101/ceramic/liveness')` it will resolve. Without the origin, you'll see an error. We currently require you to specify the transport as we only http at the moment and you may want an https front end.
This feels a bit clunky. The service trait gets a lot nicer in hyper 1.0 (or if using something like axum). It might be worth considering moving updating the open API generator to support 1.0, or move away from it if we're going to need more standard web server features.
```
❯ curl -v http://127.0.0.1:5101/ceramic/liveness
*   Trying …
```
=> feat: support cors via cli flag

.github/workflows/update-deb-repo.yml
Wanted to simplify the node update process so that they no longer needed Ansible.
A new repo for the debian package was created https://github.com/ceramicnetwork/repo
This workflow publishes rust-ceramic releases to that debian repo.
(need to merge to make sure the gpg stuff works)
=> feat: workflow update deb repo

one/src/lib.rs, p2p/src/node.rs
External swarm addresses are useful when ceramic-one is run behind a NAT. This allows explicit configuration for how remote nodes should dial the local peer.
=> feat: add option for external swarm addresses

p2p/src/swarm.rs
This was causing errors opening outgoing connections on restarts (easily noticeable running from js-ceramic and stopping/restarting the daemon repeatedly). It doesn't seem to add any benefits for our basic use so we'll default to opening outgoing connections using transient ports, which is the default behavior.
```
2024-07-16T17:46:12.102446Z DEBUG libp2p_tcp: dialing address, address: 34.27.246.129:4101
at /Users/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libp2p-tcp-0.41.0/src/lib.rs:475
in libp2p_swarm::Transport::dial with address=/dns4/bootstrap-tnet-rust-ceramic-2.3box.io/tcp/4101/p2p/12D3KooWPFGbRHWfDaWt5MFFeqAHBBq3v5BqeJ4X7pmn2V1t6uNs
2024-07-16T17:46:12.102747Z TRACE libp2p_tcp: Binding dial socket to listen socket address, address: 0.0.0.0:4101
at …
```
=> fix: disable libp2p tcp port reuse

one/src/lib.rs
With this change at startup there's a message like
```
2024-07-24T21:40:00.705970Z  INFO ceramic_one: starting api server at address 127.0.0.1:5101
at one/src/lib.rs:575
```
It does make me wonder though if we should separate `bind_address` into separate args for the port to use and the network interface to bind to.  It's kind of weird to print `127.0.0.1:5101` when presumably we also accept connections that don't just come from localhost.  Really it's the port that's going to be the most interesting part for most people
=> feat: Log bind address at startup

api-server/.openapi-generator/FILES, api-server/README.md, api-server/api/openapi.yaml, api-server/docs/NetworkInfo.md, api-server/docs/default_api.md, api-server/examples/client/main.rs, api-server/examples/server/server.rs, api-server/src/client/mod.rs, api-server/src/lib.rs, api-server/src/models.rs, api-server/src/server/mod.rs, api/ceramic.yaml, api/src/server.rs, core/src/network.rs, one/src/lib.rs
This adds a new endpoint to support retrieving the current network the server is connected to. I changing the name formatting to remove `/ceramic/` and return the values that match more closely to what we previously used in js-ceramic. It is possibly a subtly breaking change if people were relying on this string representation to match the pubsub topics, but I can't find any uses in the repo, http client or keramik so went ahead and changed it. Open to implementing `Display` or another function instead if others deem that worthwhile.
I also added `inmemory` as an alias of `in-memory` for the network cli flag so either can be passed in. It's not advertised in help/completion but it will work if passed in.
```bash
❯ curl http://127.0.0.1:5101/ceramic/config/network
{"name":"local-0"}
```
=> feat: expose current ceramic network via api

Cargo.lock, p2p/Cargo.toml, p2p/src/swarm.rs, store/src/sql/access/event.rs
If the system dns conf is missing nameservers, dns queries will never be resolved. Currently, hickory-dns doesn't error in this case so we handle it manually until the fix is released. This happens on osx if wifi is disabled when you start c1 and is never able to resolve itself without this change, even after connectivity returns. However, if the interface is active when the process starts and then wifi is disabled, it will resolve itself and we will use whatever was defined in resolv.conf.
=> fix: use default (google) dns servers if system resolv.conf is invalid

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Log bind address at startup (#446)
- Expose current ceramic network via api (#441)
- Track version history in database (#409)
- Disable libp2p tcp port reuse (#440)
- Use default (google) dns servers if system resolv.conf is invalid (#447)
=> chore: version v0.30.0

ci-scripts/schedule_k8s_deploy.sh
This workflow should just update the ceramic-one image. The js-ceramic image will be replaced by the code in [this](https://github.com/ceramicnetwork/js-ceramic/pull/3272) PR.
=> feat: don't deploy js-ceramic when deploying ceramic-one

api-server/README.md, api-server/src/lib.rs, api-server/src/models.rs, beetle/iroh-bitswap/src/server/decision.rs, ci-scripts/gen_api_server.sh, ci-scripts/gen_kubo_rpc_server.sh, kubo-rpc-server/README.md, kubo-rpc-server/src/lib.rs, kubo-rpc-server/src/models.rs, recon/src/libp2p/handler.rs
Modified the server generator scripts to ignore some new warnings and removed some unused code. I considered upgrading the generator to version 7.7.0 as it removes the duplicate allow_unused statements, but it didn't compile when I regenerated the server. 
It looks like axum support is in beta and hyper 1.0 support was merged but I'm not sure the ETA on arrival. Maybe a breaking release in September, which would be nice to have.
=> chore: rust 1.80 lints

api-server/README.md, api-server/api/openapi.yaml, api-server/docs/Event.md, api-server/docs/default_api.md, api-server/examples/client/main.rs, api-server/examples/server/server.rs, api-server/src/client/mod.rs, api-server/src/lib.rs, api-server/src/models.rs, api-server/src/server/mod.rs, api/ceramic.yaml, api/src/lib.rs, api/src/server.rs, api/src/tests.rs, service/src/event/ordering_task.rs, service/src/event/store.rs, service/src/tests/event.rs, service/src/tests/ordering.rs, store/src/metrics.rs, store/src/sql/access/event.rs, store/src/sql/entities/event_block.rs, store/src/sql/entities/mod.rs, store/src/sql/entities/utils.rs, store/src/sql/query.rs
There is now an enum parameter called `includeData` that can be `none` or `full`. I originally had a boolean, so it's not the best name and open to suggestions. I also changed the data field to return null instead of an empty string to avoid crashing multibase decoding (need to verify js-ceramic is okay with this but it doesn't use the value currently).
Example usage: `curl -v --location 'http://127.0.0.1:5001/ceramic/feed/events?includeData=full&limit=1` and `curl -v --location 'http://127.0.0.1:5001/ceramic/feed/events?limit=1`
```json
{
"events": [
{
"id": "bafyreia2ihx26sxlukdpnjzkpkyi4flmyxrwq4ritcbwxlxxyf2qltiyhq",
"data": "mOqJlcm9vdHOB2CpYJQABcRIgGkHvr0rroob2pyp6sI4VbMXjaHIomINrrvfBdQXNGDxndmVyc2lvbgHLAQFxEiAaQe+vSuuihvanKnqwjhVsxeNociiYg2uu98F1Bc0YPKJkZGF0YaJhYQFhYgJmaGVhZGVypGNzZ …
```
=> feat: add query parameter to return event data on feed endpoint

.github/workflows/create-release-pr.yml
...so that they're not all created using my token.
[This](https://github.com/ceramicnetwork/rust-ceramic/pull/453) is an example of what they'll look like now.
=> fix: create release prs via bot

api-server/README.md, api-server/api/openapi.yaml, api-server/docs/default_api.md, api-server/examples/client/main.rs, api-server/examples/server/server.rs, api-server/src/client/mod.rs, api-server/src/lib.rs, api-server/src/server/mod.rs, api/ceramic.yaml, api/src/server.rs, api/src/tests.rs
Add simple ability to filter interests by a peer. Useful in debugging the interests for a local node.
=> feat: add peer id filter to interests

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Don't deploy js-ceramic when deploying ceramic-one (#451)
- Add query parameter to return event data on feed endpoint (#398)
- Add peer id filter to interests (#456)
- Fix benchmark (#410)
- Create release prs via bot (#454)
- Revert to using pat for release prs (╯°□°)╯︵ ┻━┻ (#458)
- Rust 1.80 lints (#450)
=> chore: version v0.31.0

Cargo.lock, Cargo.toml, one/Cargo.toml, one/src/lib.rs, one/src/migrations.rs
BREAKING CHANGE: We've decided to change the default storage location back to a shared location (`$HOME/.ceramic-one` or `./.ceramic-one` if home cannot be determined). While I believe the reasoning in #431 was sound, we've decided to optimize for the unboxing experience where things "just work" no matter where you run ceramic-one, rather than experienced users or operators who will likely want to provide a directory and run multiple nodes.
Rather than simply revert that PR, I made a slight change to show the default value in the command line help, which was previously not the case when we used the shared location.
```
-s, --store-dir <STORE_DIR>
Path to storage directory. The default is ~/.ceramic-one [env: CERAMIC_ONE_STORE_DIR=] [default: /Users/david/.ceramic-one]
-p, --p2p-key-dir …
```
=> feat: change default dir back to shared home location

api/src/lib.rs, api/src/server.rs, api/src/tests.rs, p2p/src/node.rs, recon/src/client.rs, recon/src/libp2p/protocol.rs, recon/src/libp2p/tests.rs, recon/src/protocol.rs, recon/src/recon.rs, recon/src/recon/btreestore.rs, recon/src/recon/tests.rs, service/src/event/migration.rs, service/src/event/order_events.rs, service/src/event/ordering_task.rs, service/src/event/service.rs, service/src/event/store.rs, service/src/interest/store.rs, service/src/tests/event.rs, service/src/tests/interest.rs, service/src/tests/mod.rs, service/src/tests/ordering.rs, store/src/metrics.rs
The main feature added is some basic insert batching in recon. Originally, we thought we might use a channel and manage the result of batches outside of the recon protocol, but it would require substantial changes to make it work without reading its writes currently. If we add RedTree or another in memory state to capture the known keys before persisting them, that would work. In the end, this only really ends up batching writes if we're receiving a lot of values without sending ranges. Previously we always inserted every key immediately, so this should still be an improvement but it will require benchmarking to say for certain. The messages may arrive in a slightly different order, but the non-deterministic word order test passes fine, as does a new test using disjoint and demonstrating …
=> feat: recon event insert batching

service/src/event/order_events.rs, service/src/event/ordering_task.rs, service/src/event/service.rs, store/src/lib.rs, store/src/sql/access/event.rs, store/src/sql/entities/event.rs, store/src/sql/entities/mod.rs, store/src/sql/test.rs
Removes the EventInsertableBody type and pushes its fields up into the parent EventInsertable
=> chore: Flatten EventInsertable type

service/src/event/order_events.rs, service/src/event/ordering_task.rs, store/src/sql/entities/event.rs
Builds on https://github.com/ceramicnetwork/rust-ceramic/pull/480
=> chore: Remove Clone from EventInsertable

CODEOWNERS, Cargo.lock, Cargo.toml, olap/Cargo.toml, olap/src/aggregator.rs, olap/src/lib.rs, olap/src/main.rs, olap/src/metrics.rs
The ceramic-olap binary copies verbatim some setup code from ceramic-one re tracing/logging/metrics. Eventually this may move back into the ceramic-one binary or we can find a way to make it generic and reuse. Given this is only the first copy of the code I don't think we should work to make it generic yet. Not until we either decide this is the long term home for the ceramic-olap binary or have a third binary we want to have a similar setup.
This binary does nothing yet except start tracing/logging/metrics and then wait for a signal to shutdown gracefully.
=> feat: add noop ceramic-olap binary

api/src/server/event.rs, event/src/unvalidated/event.rs, event/src/unvalidated/signed/mod.rs, service/src/event/order_events.rs, service/src/event/ordering_task.rs, service/src/event/service.rs, service/src/tests/migration.rs, service/src/tests/mod.rs, store/src/sql/access/event.rs, store/src/sql/entities/event.rs
Also changes a bunch of places to use references to Cids instead of returning or taking by value.  Cid implements Copy which means there might a lot of silent copying happening under the hood without it being obvious from the code, and since Cids can be larger than a memory address, using references where possible seems prudent.  Have that change split into its own commit if you want to see the changes separately.  Can also split into two PRs if preferred.
=> chore: Remove EventMetadata type

event/Cargo.toml, event/src/unvalidated/signed/cacao.rs, validation/src/signature/pkh_ethereum.rs, validation/src/siwx_message.rs, validation/src/verifier/cacao_verifier.rs
In order to ensure that CACAOs round trip without changing the CID, we use a string when deserializing rather than a chrono::DateTime which can change the second precision that was originally included. It's a bit clunky, open to better ideas.
=> fix: use cacao timestamp strings and parse

event/src/unvalidated/signed/cacao.rs, validation/src/verifier/cacao_verifier.rs
Adds a method to the CACAO verifier trait to check that the provide resources are valid for the given stream. I may end up changing the parameters but these should all be known so I think this will work. Based on the [js-ceramic](https://github.com/ceramicnetwork/js-ceramic/blob/a342f204dfcc0952aa691249e17d09d53af35036/packages/stream-handler-common/src/signature_utils.ts#L77) code. Targets #498.
=> feat: check cacao resources against stream information

Cargo.toml, one/src/feature_flags.rs, one/src/lib.rs, one/src/migrations.rs, p2p/src/node.rs, service/src/event/service.rs, service/src/lib.rs, service/src/tests/event.rs, service/src/tests/migration.rs, service/src/tests/ordering.rs, store/benches/sqlite_store.rs, store/src/sql/entities/event.rs
Cleaned up some oversights like not adding the new crate to the workspace dependencies list and the benchmark not compiling. Also put an `Arc` around the event on `EventInsertable` so I can clone it to track in a map for the event validation work.
The main change is adding a new experimental feature flag that event validation is behind. It's a sub optimal representation, but my intention is that it's temporary and allows me to merge changes in #503 so we can benchmark and test more thoroughly before it's on everywhere, at which point the feature flag will be removed and it's the configured behavior. It's enabled with `--experimental-feature-flags event-validation`.
All of these changes were part of #503, so I'll rebase that one to use this as the source since these should be standalone …
=> feat: groundwork for event validation and some clean up

one/src/migrations.rs, service/src/event/migration.rs, service/src/event/service.rs, service/src/tests/migration.rs
With this change we catch two more cases where we can detect tile docs. Additionally by default we only count the number of tile docs we find and do not log any errors about them. This way any tile docs do not create a feeling of failure when migrating.
=> fix: updates detection of tile docs and doesn't log them by default

event-svc/src/event/service.rs, event-svc/src/tests/event.rs, one/src/daemon.rs, one/src/lib.rs, one/src/migrations.rs, p2p/src/node.rs
This removes some of the abstraction around sqlite to make creating and initializing services more straightforward. We will likely need to add new abstractions when we want to support parquet or other storage formats however those can be service focused instead of db focused.
=> refactor: simplify daemon logic

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Make feature flags top level with experimental features requiring the experimental-features flag to be set (#521)
- Api to transform events to conclusion events (#508)
- Add flight sql server to expose conclusion feed. (#523)
- Anchor service (#484)
- Add metamodel stream id constant (#529)
- Infer stream type from raw event model and add it to conclusion event + tests (#525)
- Rpc client for eth blockchains (#520)
- Verify time event proofs from eth rpc client and calculate time (#522)
- Disable debian repo release workflow (#519)
- Use build.rs to rebuild sql crate on migrations change (#531)
- More prep for signed event validation (#526)
=> chore: version v0.36.0

p2p/src/swarm.rs
Spawn a std thread instead of using a tokio block_on. Basically reverting a change I made a while ago that was a mistake. This non std version causes a task to be "busy" indefinitely, which may be the reason we were seeing things lock up on really small machines.
=> fix: spawn std task to avoid blocking runtime

event-svc/src/event/ordering_task.rs, event-svc/src/event/service.rs, event-svc/src/event/validator/event.rs, event-svc/src/event/validator/grouped.rs, event-svc/src/event/validator/mod.rs, event-svc/src/event/validator/signed.rs, event-svc/src/tests/mod.rs, event-svc/src/tests/ordering.rs
Initial implementation of validation for signed events. The Validation module accepts the list of events, partitions them into "time" and "signed" events and delegates the validation to the appropriate handler. 
The signed validator will validate events against the init controller and if it's unable to find the init event, will consider them unvalidated. The service decides whether this is an error or acceptable based on the `ValidationRequirement` `allow_pending` value. If pending is supported, they are tracked in memory until the required init event is found, otherwise they are considered an error.
When verifying against the init event we check the CACAO resources, the CACAO and envelope signatures and the delegation chain, but we currently assume all streams are MIDs when constructing …
=> feat: validate signed events

event-svc/src/event/order_events.rs, event-svc/src/event/ordering_task.rs, event-svc/src/event/service.rs, event-svc/src/event/store.rs, event-svc/src/event/validator/event.rs, event-svc/src/store/sql/access/event.rs, event-svc/src/store/sql/entities/event.rs, event-svc/src/store/sql/test.rs, event-svc/src/tests/event.rs, event-svc/src/tests/mod.rs
This PR refactors some of the code for the event service and store to do less cloning/copying of data, and do less database IO when we don't actually care. The commits should all pass tests independently, so we don't have to take all of them (or if any of the later commits are more contentious, I can move them to a separate PR).
Now when creating `EventInsertable` objects during validation, we mark the event as deliverable if it's an init event. This was one of the responsibilities of the first pass of "ordering" that has been obviated. Next, the first pass of ordering was modified to support only ordering against the in memory set as a "best effort" or using the database to ensure the complete history exists. For recon and migrations, this means we can do less work. 
Previously, we would …
=> refactor: return reference to inserted item from event store and reduce unnecessary ordering work 

one/src/migrations.rs
When migrating from IPFS there are two possible directory structures, a sharded and a non sharded form. This change now supports both defaulting to the sharded form.
=> feat: support non sharded IPFS block paths

Cargo.lock, flight/src/server.rs, olap/Cargo.toml, olap/src/aggregator/ceramic_patch.rs, olap/src/aggregator/mod.rs, olap/src/lib.rs
With this change the doc_state table is backed by an object store instead of the local filesystem.
We assume an S3 compatible API and credentials.
Fixes AES-284
=> feat: store doc_state table in object storage

event-svc/src/event/service.rs, event-svc/src/event/store.rs, event-svc/src/event/validator/event.rs, event-svc/src/event/validator/signed.rs
The pending/invalid logic didn't fit very nicely as implemented in #503. With #530 (this one's target), the return types of some of these signatures have been adjusted and it made the change to have the validator know whether a missing init event should be an error or pending/unvalidated easier. This feels like a more appropriate place to understand this, and simplifies the service logic a bit. 
It also adjusts how the event validator is constructed by the service so that we create one that we reuse, which will make it easier to construct at start up with the eth RPC providers to actually do the time event chain inclusion validation.
=> refactor: teach event validator some more and store a copy on the service

event-svc/src/event/service.rs, event-svc/src/event/store.rs, event-svc/src/event/validator/event.rs, event-svc/src/event/validator/mod.rs, event-svc/src/event/validator/time.rs, event-svc/src/tests/event.rs, one/src/daemon.rs, one/src/migrations.rs, p2p/src/node.rs
The validation service now sets up and interacts with the ethereum RPC providers in order to validate time event inclusion proofs. I refactored some things a bit, like removing a trait in the service crate that isn't necessary currently as we already have one at the RPC provider level. 
The `ValidationRequirement` struct now has a `require_inclusion_proof` option that allows us to store and sync time events over recon even if we can't prove that their valid (e.g. we don't have an RPC provider for the chain). If we can prove they are invalid, we will reject them still. I also made an error enum that is specific to the chain inclusion result to make it easier to process different errors. It doesn't yet handle transient errors very well, which I plan to address in the RPC provider level when …
=> feat: validate time event chain inclusion proofs

Cargo.lock, anchor-service/src/anchor_batch.rs, anchor-service/src/time_event.rs, event-svc/src/event/validator/time.rs, one/src/daemon.rs, validation/Cargo.toml, validation/src/blockchain/eth_rpc/http.rs, validation/src/blockchain/eth_rpc/mod.rs, validation/src/blockchain/eth_rpc/types.rs, validation/src/blockchain/mod.rs, validation/src/lib.rs, validation/src/signature/mod.rs, validation/src/signature/pkh_ethereum.rs, validation/src/test.rs, validation/src/verifier/cacao_verifier.rs, validation/src/verifier/event_verifier.rs, validation/src/verifier/mod.rs, validation/src/verifier/opts.rs
Currently targets #539.
Done in a series of commits for easier review, the main changes are to add [alloy](https://github.com/alloy-rs/alloy) as the ethereum RPC provider and add more nuanced errors to the trait. The event service currently doesn't retry these transient errors, but it has the ability to do so in the future. This will make it easier to implement self anchoring as alloy understands solidity ABI and signing. I am still using/parsing transaction input from a hex encoded string rather than bytes with the `alloy::sol!`macro but that change could be made as well.
I split the `eth_rpc` module into files first, then adjusted some types in order to make it easier to see the specific swap to alloy. It required updating dependencies as a tower version failed to compile. I also took …
=> refactor: use alloy as ethereum RPC provider

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Validate signed events (#503)
- Self-anchoring (part 5) (#488)
- Support non sharded IPFS block paths (#541)
- Store doc_state table in object storage (#540)
- Add logic to migration to count errors by model (#542)
- Validate time event chain inclusion proofs (#539)
- Process batches on the interval (#548)
- Ethereum RPC provider configuration (#547)
- Make self-anchoring config experimental (#546)
- Return reference to inserted item from event store and reduce unnecessary ordering work  (#530)
- Teach event validator some more and store a copy on the service (#536)
- Use alloy as ethereum RPC provider (#543)
- Update ca-certificates so eth rpc connections (#549)
=> chore: version v0.38.0

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Allow local and inmemory networks to start up without an eth rpc url (#555)
- Always log options at startup (#554)
=> chore: version v0.39.0

event-svc/src/event/migration.rs
The migration would write out the error counts file even if there were no errors leaving an extra file in the repo. This was confusing as this even occurred during tests. Now if there are no errors the file is not created.
=> fix: only write out error counts on errors

Cargo.lock, event-svc/src/event/migration.rs, event-svc/src/tests/migration.rs, one/Cargo.toml, one/src/migrations.rs
This PR adds support for migrating IPFS blocks from an input file list. It also introduces both an `offset` and a `limit` that can be used to paginate migrations, whether from a directory or from a file list.
This is needed for being able to apply incremental ZFS snapshots without having to re-migrate the entire blockstore. The list of added blocks can be extracted from the incremental snapshot and input to the migration so that only new blocks are migrated. This will dramatically reduce the amount of time needed for migrating new blocks added after the first snapshot was taken.
Note that paginating over a directory might have unpredictable results if it is receiving live updates.
=> feat: migrate from file list

anchor-service/src/anchor_batch.rs
This leverages the time math of skipping missed ticks etc. We are only left with computing the time when we should start the first tick. For this we use chrono and then rely on Interval for the heavy lifting.
=> fix: use tokio::time::Interval for scheduling anchor batches

api/src/server.rs, api/src/tests.rs, one/src/daemon.rs
We previously relied on http server shutdown closing the channel to signal the task to stop, which could take at least one tick interval of the task to trigger. Now, we listen to the daemon shutdown signal so it's faster.
=> fix: subscribe to server shutdown signal in insert task

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Protect FlightSQL server with sql options. (#544)
- Aes 291 continuous queries in olap aggregator (#538)
- Migrate from file list (#501)
- Use data container wrapper for mutable metadata (#559)
- Add query command to ceramic-one (#545)
- Only write out error counts on errors (#560)
- Use correct index for the conclusion feed. (#561)
- Use tokio::time::Interval for scheduling anchor batches (#563)
- Subscribe to server shutdown signal in insert task (#553)
- Record the per item duration of an insert_many request (#551)
=> chore: version v0.40.0

.gitignore, Cargo.lock, event-svc/Cargo.toml, event-svc/src/event/validator/event.rs, event-svc/src/event/validator/time.rs, one/src/daemon.rs, validation/src/blockchain/eth_rpc/http.rs, validation/src/blockchain/eth_rpc/mod.rs, validation/src/blockchain/eth_rpc/types.rs
I modified the EthRpc trait exposed by the validation crate to hide more chain information and return the specific information needed to do time event validation (a timestamp and a root CID). The parsing and understanding of various transaction input related information moved from the service to the validation crate. A lot of code was moved, some was deleted/renamed (specifically `EthRpc` to `ChainInclusion` trait and the related inputs/outputs). The `ChainInclusion` trait has an associated type for the input so chains without the same Eth RPC interface can request different information.
=> refactor: modify eth rpc trait for other chains

anchor-remote/src/cas_remote.rs, anchor-service/src/anchor.rs, anchor-service/src/cas_mock.rs, anchor-service/src/transaction_manager.rs, event-svc/src/event/migration.rs, event-svc/src/event/mod.rs, event-svc/src/event/service.rs, event-svc/src/event/validator/event.rs, event-svc/src/event/validator/mod.rs, event-svc/src/event/validator/time.rs, event-svc/src/lib.rs, event/src/unvalidated/builder.rs, event/src/unvalidated/event.rs, one/src/daemon.rs, validation/src/blockchain/eth_rpc/http.rs, validation/src/blockchain/eth_rpc/mod.rs, validation/src/blockchain/eth_rpc/types.rs
builds on https://github.com/ceramicnetwork/rust-ceramic/pull/550 making things more fully generic and preparing for the addition of an "adm" implementation of the `ChainProvider` trait.
=> refactor: make ChainInclusion trait fully generic and change input to the raw AnchorProof

one/src/daemon.rs
Do not merge - for now
I am collecting evidence that this feature has been stable on durable for over a 1 week
=> feat: turn on event validation by default

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Turn on event validation by default (#562)
- Correct path to latest tarball (#566)
- Size 1 anchor trees (#565)
- Modify ethereum rpc trait for hoku support (#550)
- Make ChainInclusion trait fully generic and change input to the raw AnchorProof (#570)
=> chore: version v0.41.0

validation/src/verifier/cacao_verifier.rs
I included a $ in the string interpolation like I was writing javascript (that's what I get for copying from js-ceramic). Now that's removed so it actually compares the model stream ID instead of the literal `${streamID}`.
=> fix: fix cacao model auth check

validation/src/verifier/cacao_verifier.rs
I'm mostly just curious how far the js-ceramic tests will get with event validation turned on with this change.
=> fix: Make error message match the js-ceramic version

Cargo.lock, Cargo.toml, flight/tests/server.rs, one/src/daemon.rs, pipeline/Cargo.toml, pipeline/src/aggregator/mod.rs, pipeline/src/cache_table.rs, pipeline/src/conclusion/table.rs, pipeline/src/config.rs, pipeline/src/lib.rs, pipeline/src/schemas.rs, pipeline/src/tests.rs
Prior to this change each small batch of writes into the API would result in a single parquet file being written to object store. This behavior quickly creates many files that are too small to gain any column storage benefits. 
This change instead caches writes locally into an in memory table that once large enough is written as a single file into object store. This has a few consequences:
* Files written to object store are large enough to be valuable. (defaults to 10,000 rows)
* There is always a set of data that lives only in memory.
* If the process is stopped or crashes this data must be recreated on next startup
* This data can only be queried if read directly from the node that holds the data
=> feat: use cache table to make queries faster and writes to object store batched

one/src/daemon.rs, p2p/src/behaviour/ceramic_peer_manager.rs, p2p/src/node.rs, recon/src/libp2p.rs, recon/src/libp2p/handler.rs, recon/src/libp2p/stream_set.rs, recon/src/libp2p/tests.rs
With this change peers will backoff synchronization attempts with peers that fail synchronization. This will have the effect that the bootstrap nodes do not talk to nodes that are sending bad data very often.
However the backoff state is tied to the connection state and is reset if the connection resets. Allowing developers to restart their node and be in good standing with bootstrap nodes.
Additionally a small change was added to prefer using the connected address to a peer when reporting the address of connected peers.
=> feat: backoff recon synchronization to peers with bad data

api/src/server.rs, api/src/tests.rs, core/src/event_id.rs
Prior to this change a write of the same data (keyed by the event id) would cause an error the batching logic of the write path. It was assumed that double writes would not happen and so the channel to report the insert result was dropped, causing an error.
Now all channels are preserved and the result is sent to all.
=> fix: handle double write of same data

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Add api to get stream state ([#586](https://github.com/ceramicnetwork/rust-ceramic/issues/586))
- Expose various db errors when storing events ([#601](https://github.com/ceramicnetwork/rust-ceramic/issues/601))
- Handle double write of same data ([#613](https://github.com/ceramicnetwork/rust-ceramic/issues/613))
- Automatically select release level ([#612](https://github.com/ceramicnetwork/rust-ceramic/issues/612))
=> chore: version v0.45.0

event-svc/src/event/ordering_task.rs
This should tell us how far we've made it in addition to how many events we've had to process so far.
=> chore: log current highwater mark when processing events

Cargo.lock, Cargo.toml, event-svc/src/event/ordering_task.rs, one/src/daemon.rs, sql/src/sqlite.rs
We previously ran optimize on shutdown, but the [sqlite docs](https://www.sqlite.org/pragma.html#pragma_optimize) recommend setting the value to `0x10002` and then run `PRAGMA optimize` daily. Now we do that when starting the ceramic one daemon. Also updated sqlx to the newest version and added a test to show the start up ordering task exits when it's unable to process events.
=> chore: run sqlite optimize at startup and interval

Dockerfile, api/src/server.rs, api/src/tests.rs, event-svc/src/event/store.rs, event-svc/src/store/metrics.rs, event-svc/src/store/sql/access/event.rs, event-svc/src/store/sql/query.rs, event-svc/src/store/sql/test.rs, event-svc/src/tests/event.rs, event-svc/src/tests/migration.rs, event-svc/src/tests/mod.rs, interest-svc/src/interest/store.rs, interest-svc/src/store/metrics.rs, interest-svc/src/store/sql/access/interest.rs, interest-svc/src/store/sql/entities/mod.rs, interest-svc/src/store/sql/entities/order_key.rs, interest-svc/src/store/sql/query.rs, interest-svc/src/tests/interest.rs, p2p/src/node.rs, recon/src/libp2p/tests.rs, recon/src/protocol.rs, recon/src/recon.rs, recon/src/recon/btreestore.rs
This change removes the offset/limit pagination pattern where it implies a more flexible API than was needed or used. Having the flexible API meant that casts from usize to smaller types for limits and offsets could break pagination assumptions. Now with this change more specific APIs are exposed where its safe to make assumptions about the size of limit offset values in queries.
Additionally in the API where true pagination was the desired API u32 is used instead of usize to keep page sizes small.
Finally, the range_with_values method on the Recon trait was removed as it was unused
=> refactor: remove offset/limit where too generic

Cargo.lock, flight/tests/server.rs, one/Cargo.toml, one/src/daemon.rs, pipeline/src/aggregator/mod.rs, pipeline/src/config.rs, pipeline/src/lib.rs
Testing and developing ceramic-one is much easier with fewer dependencies. This change makes it so that an s3 API compatible object store is not required. Rather objects can be stored on local disk.
=> feat: add support for local file object store

Cargo.lock, Cargo.toml, event-svc/src/event/ordering_task.rs, one/src/daemon.rs, one/src/lib.rs, one/src/migrations.rs, sql/src/sqlite.rs
Calling optimize when setting up the connection pool could timeout on big databases. Apparently `acquire_timeout` applies to all statements executed at startup. This also removes the `acquire_timeout` override and uses the default of 30 seconds, continues processing the ordering task loop when there's a "transient" error and, and allows specifying a few sqlite pragmas from the command line which may improve performance (`mmap_size`, `cache_size`, `temp_store`, `analysis_limit`) and a max number of read only connections for the pool (default is 8).
Analysis limit is a bit odd, as it has a default of 1000 and needs to be negative to be disabled. I don't think you can set a clap default to `Some(val)` and have the cli set it to none, but maybe I missed something. If that value is set, we run …
=> fix: sqlite optimize during connect could timeout and allow specifying db options

Cargo.lock, Cargo.toml
The needed changes from main have merged and been released. We can use a released version of arrow deps now.
=> chore: use arrow release 53.3

anchor-service/src/anchor_batch.rs, event-svc/src/event/ordering_task.rs, event-svc/src/event/service.rs, event-svc/src/store/sql/access/event.rs, event-svc/src/store/sql/query.rs, event-svc/src/store/sql/test.rs, event-svc/src/tests/event.rs, event-svc/src/tests/mod.rs, flight/tests/server.rs
After an IPFS migration, we have to review all the data in the database to make sure we have the complete stream history before we can send events out of the API. We originally kept it simple and would read events and process them, then repeat in a single task. This was taking far too long on large datasets (e.g. 100s of GBs). Now we spawn multiple tasks to read the events from the database, and they send events over a channel to the ordering task (like we do during normal operation). This task was also modified to spawn multiple tasks to process events by stream and order them. Both changes appeared necessary during testing as one side would waiting on the other. This allows us to keep a solid rate of processing going and we've seen a substantial improvement in runtime (~60-100x faster). …
=> feat: use many tasks to order streams and discover undelivered events at startup

Cargo.lock, Cargo.toml, api-server/.openapi-generator/FILES, api-server/README.md, api-server/api/openapi.yaml, api-server/docs/Peer.md, api-server/docs/Peers.md, api-server/docs/default_api.md, api-server/examples/client/main.rs, api-server/examples/server/server.rs, api-server/src/client/mod.rs, api-server/src/lib.rs, api-server/src/models.rs, api-server/src/server/mod.rs, api/Cargo.toml, api/ceramic.yaml, api/src/lib.rs, api/src/server.rs, api/src/tests.rs, core/src/lib.rs, core/src/peer.rs, one/src/daemon.rs, one/src/network.rs
With this change a new API endpoint is added for accessing connected peers. The API is similar to the /api/v0/swarm/peers endpoint however it allows for multiple addresses and does not have to remain Kubo RPC compatible.
The endpoint allows posting an address and therefore connecting to a new peer.
Fixes: #608
=> feat: adds /peers endpoint

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Add peer entry and peer key structs ([#615](https://github.com/ceramicnetwork/rust-ceramic/issues/615))
- Add support for local file object store ([#623](https://github.com/ceramicnetwork/rust-ceramic/issues/623))
- Add support for prepared statements ([#600](https://github.com/ceramicnetwork/rust-ceramic/issues/600))
- Add peer recon ring ([#616](https://github.com/ceramicnetwork/rust-ceramic/issues/616))
- Use many tasks to order streams and discover undelivered events at startup ([#620](https://github.com/ceramicnetwork/rust-ceramic/issues/620))
- Adds transitive sharing of peer information ([#618](https://github.com/ceramicnetwork/rust-ceramic/issues/618))
- Adds /peers endpoint ([#628](https://github.com/ceramicnetwork/rust-ceramic/issues/628))
- Sqlite optimize during connect …
=> chore: version v0.46.0

one/src/daemon.rs, one/src/network.rs, p2p/src/behaviour.rs, p2p/src/node.rs, p2p/src/swarm.rs, p2p/tests/node.rs, recon/src/libp2p.rs, recon/src/libp2p/handler.rs, recon/src/libp2p/stream_set.rs, recon/src/libp2p/tests.rs
With this change the interests ring is no longer synchronized between peers. A local node will still use the interest-svc to know its own interests and the beginning of each Recon conversation negotiates shared interests. Therefore it is no longer necessary to synchronize interests.
In the future we may decide that we want to use Recon to sync interests instead of a linear sharing of interests before each conversation, however that is only a performance optimization that is not important at this stage.
Fixes #610
Fixes #611
=> feat: stop synchronizing interests

event-svc/src/event/mod.rs, event-svc/src/event/ordering_task.rs, event-svc/src/event/service.rs, event-svc/src/lib.rs, event-svc/src/tests/event.rs, one/src/daemon.rs, one/src/migrations.rs, p2p/tests/node.rs, peer-svc/src/tests/peer.rs
The ordering tasks wouldn't shutdown gracefully and could take forever. Worst case you killed the process and left a lock on the sqlite file and had to go find another pid to kill it. Now they exit with sigint.
=> fix: shutdown ordering tasks with sigint

.github/workflows/publish-prerelease.yml, .github/workflows/update-homebrew.yml, ci-scripts/package.sh
This week github updated the `ubuntu-latest` tag to be ubuntu-24.04. This meant that version 0.47.0 of ceramic-one no longer runs on ubuntu-22. This is unexpected and not in our control. With this change we explicitly name the os versions we target (this matters because of glibc versions). This means we will need to add new versions and deprecate old versions as they are released.
=> chore: use explicit os versions

one/src/lib.rs, validation/src/blockchain/eth_rpc/http.rs
The previous default would report that tx did not exist when looked up by hash. This new url works without issue. Also increase the cache size to reduce the chances of being rate limited.
Now standing up a local node can successfully synchronize with the bootstrap nodes without being rate limited.
=> fix: use new default testnet eth rpc url

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Use new default testnet eth rpc url ([#638](https://github.com/ceramicnetwork/rust-ceramic/issues/638))
- Add tests for eip55 cacaos ([#636](https://github.com/ceramicnetwork/rust-ceramic/issues/636))
=> chore: version v0.47.3

pipeline/src/aggregator/mod.rs, pipeline/src/concluder/mod.rs, pipeline/src/tests.rs
The bug was a misunderstanding of how select! branches work. We were stuck forever in a select branch because we did not handle the Ok case. This has been fixed and we have tests.
=> fix: conclusion poll loop no longer stops

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Adds actor framework ([#644](https://github.com/ceramicnetwork/rust-ceramic/issues/644))
- Stream flight sql queries ([#645](https://github.com/ceramicnetwork/rust-ceramic/issues/645))
- Add pipeline metrics ([#646](https://github.com/ceramicnetwork/rust-ceramic/issues/646))
- Update built dep ([#641](https://github.com/ceramicnetwork/rust-ceramic/issues/641))
- Fix off by one, projection and not found bugs ([#647](https://github.com/ceramicnetwork/rust-ceramic/issues/647))
- Conclusion poll loop no longer stops ([#648](https://github.com/ceramicnetwork/rust-ceramic/issues/648))
- Add simpler shutdown handling ([#643](https://github.com/ceramicnetwork/rust-ceramic/issues/643))
- Rename _stream tables to _feed ([#649](https://github.com/ceramicnetwork/rust-ceramic/issues/649))
- Make …
=> chore: version v0.48.0

pipeline/src/cid_string.rs, pipeline/src/lib.rs, pipeline/src/stream_id_string.rs
This UDF is helpful in decoding the model dimension as it is a stream id bytes.
For example this query:
```sql
SELECT stream_id_string(array_extract(map_extract(dimensions, 'model'), 1)) FROM event_states WHERE ...
```
=> feat: adds stream_id_string udf

pipeline/src/dimension_extract.rs, pipeline/src/lib.rs
Simplifies a query like
```sql
SELECT stream_id_string(array_extract(map_extract(dimensions, 'model'), 1)) FROM event_states WHERE ...
```
to
```sql
SELECT stream_id_string(dimension_extract(dimensions, 'model')) FROM event_states WHERE ...
```
=> feat: add dimension_extract udf

pipeline/src/cid_string.rs, pipeline/src/stream_id_string.rs
This is a more efficient list UDF implementation when the list structure does not change. We simply map over the values array directly and reuse the list offsets and nulls.
This is not strictly necessary. However setting a standard to always operate on a single Arrow array at a time is kinda the whole point of Arrow. Therefore I thinks is valuable to make this change so we set a good pattern to follow in the future.
=> refactor: more efficient list udf impls

Cargo.lock, pipeline/src/aggregator/mod.rs, pipeline/src/cache_table.rs, pipeline/src/cid_part.rs, pipeline/src/lib.rs, pipeline/src/schemas.rs
BREAKING CHANGE:
This change is breaking to the structure of the event_states table in object store. With this change any existing data in the event_states object store is invalidated. On the next startup the data will be recomputed from the conclusion_events table. It is recommended once a successful upgrade is complete to delete the old parquet files for the event_states table from object store, as that data will no longer be read in its current form. The old parquet files will be in the `ceramic/v0/event_states/` directory. The new parquet files are in `ceramic/rev1/event_states/` directory.
This change achieve two main improvements:
1. By partitioning the event_states table by the event_cid the join to aggregate a new event with its previous event is much more efficient.
2. In some …
=> feat: partition event states by event cid

Cargo.lock, one/Cargo.toml, one/src/query.rs
With this change it is now possible to output the results of queries in machine friendly ways.
=> feat: adds output format options to query command

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Adds stream_id_string udf ([#653](https://github.com/ceramicnetwork/rust-ceramic/issues/653))
- Add dimension_extract udf ([#654](https://github.com/ceramicnetwork/rust-ceramic/issues/654))
- Adds output format options to query command ([#659](https://github.com/ceramicnetwork/rust-ceramic/issues/659))
- [**breaking**] Partition event states by event cid ([#658](https://github.com/ceramicnetwork/rust-ceramic/issues/658))
- Use invoke_batch on UDFs as invoke is deprecated ([#652](https://github.com/ceramicnetwork/rust-ceramic/issues/652))
- Adds batching logic to conclusion-feed-table ([#656](https://github.com/ceramicnetwork/rust-ceramic/issues/656))
- More efficient list udf impls ([#657](https://github.com/ceramicnetwork/rust-ceramic/issues/657))
=> chore: version v0.49.0

.github/workflows/publish-prerelease.yml
We did not use v3 in any of the ways that break with v4 https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
=> chore: use artifacts v4 as v3 is deprecated

Cargo.lock, pipeline/Cargo.toml, pipeline/src/cid_part.rs, pipeline/src/cid_string.rs, pipeline/src/dimension_extract.rs, pipeline/src/lib.rs, pipeline/src/macros.rs, pipeline/src/stream_id_string.rs, pipeline/src/stream_id_to_cid.rs
These UDFs do simple transformations on data. These are all used as part of schema validation. They are added separately to keep the set of changes smaller.
=> feat: add/update UDFs for the ceramic pipeline

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Adds stream_id_string udf ([#653](https://github.com/ceramicnetwork/rust-ceramic/issues/653))
- Add dimension_extract udf ([#654](https://github.com/ceramicnetwork/rust-ceramic/issues/654))
- Adds output format options to query command ([#659](https://github.com/ceramicnetwork/rust-ceramic/issues/659))
- [**breaking**] Partition event states by event cid ([#658](https://github.com/ceramicnetwork/rust-ceramic/issues/658))
- Add/update UDFs for the ceramic pipeline ([#662](https://github.com/ceramicnetwork/rust-ceramic/issues/662))
- Use invoke_batch on UDFs as invoke is deprecated ([#652](https://github.com/ceramicnetwork/rust-ceramic/issues/652))
- Adds batching logic to conclusion-feed-table ([#656](https://github.com/ceramicnetwork/rust-ceramic/issues/656))
- More efficient list udf …
=> chore: version v0.50.0

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Adds stream_id_string udf ([#653](https://github.com/ceramicnetwork/rust-ceramic/issues/653))
- Add dimension_extract udf ([#654](https://github.com/ceramicnetwork/rust-ceramic/issues/654))
- Adds output format options to query command ([#659](https://github.com/ceramicnetwork/rust-ceramic/issues/659))
- [**breaking**] Partition event states by event cid ([#658](https://github.com/ceramicnetwork/rust-ceramic/issues/658))
- Add/update UDFs for the ceramic pipeline ([#662](https://github.com/ceramicnetwork/rust-ceramic/issues/662))
- Use invoke_batch on UDFs as invoke is deprecated ([#652](https://github.com/ceramicnetwork/rust-ceramic/issues/652))
- Adds batching logic to conclusion-feed-table ([#656](https://github.com/ceramicnetwork/rust-ceramic/issues/656))
- More efficient list udf …
=> chore: version v0.51.0

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Make ceramic-sdk part of the repo, promote flight sql and aggregator ([#669](https://github.com/ceramicnetwork/rust-ceramic/issues/669))
- Migrates ceramic-tests to this repo ([#668](https://github.com/ceramicnetwork/rust-ceramic/issues/668))
=> chore: version v0.53.0

one/src/lib.rs
Of the ones found on https://docs.gnosischain.com/tools/RPC%20Providers/ this is the only one that doesn't error when looking up transactions by hash. All the other would occasionally report that the transaction was not found causing sync to fail.
=> chore: use different gnosis rpc url

event-svc/src/event/migration.rs, event-svc/src/event/service.rs, event-svc/src/tests/migration.rs, one/src/migrations.rs, pipeline/src/aggregator/model_instance_validate.rs
Since ceramic-one nodes refuse to sync with nodes that share bad data its important that the migration process ensure no bad data is migrated.
This change adds the ability to validate signatures and chain ids skipping events that do not pass validation.
Additionally you can also filter events to only events for a specific model.
Finally the pipeline aggregator is more forgiving of bad data, recording validation errors for individual events instead of failing the whole aggregator pipeline.
=> feat: add some validation logic to migration from-ipfs

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Add some validation logic to migration from-ipfs ([#685](https://github.com/ceramicnetwork/rust-ceramic/issues/685))
- Make sdk use correct id in data event payloads ([#673](https://github.com/ceramicnetwork/rust-ceramic/issues/673))
- Use new default gnosis rpc endpoint ([#683](https://github.com/ceramicnetwork/rust-ceramic/issues/683))
- Remove distinct step as its prohibitively expensive ([#682](https://github.com/ceramicnetwork/rust-ceramic/issues/682))
- Do not deploy to durable envs ([#670](https://github.com/ceramicnetwork/rust-ceramic/issues/670))
- Update CODEOWNERS ([#672](https://github.com/ceramicnetwork/rust-ceramic/issues/672))
- Autogen sdk docs, ci check they are generated ([#674](https://github.com/ceramicnetwork/rust-ceramic/issues/674))
- Use different gnosis rpc url …
=> chore: version v0.54.0

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Conflict resolution scaffolding ([#687](https://github.com/ceramicnetwork/rust-ceramic/issues/687))
- Update more sdk repo urls ([#703](https://github.com/ceramicnetwork/rust-ceramic/issues/703))
- Skip private sdk packages ([#705](https://github.com/ceramicnetwork/rust-ceramic/issues/705))
- *(sdk)* Use recursive pnpm publish instead of npm publish
- Random things like feed queries, query CLI, migration logging, deps ([#708](https://github.com/ceramicnetwork/rust-ceramic/issues/708))
- *(sdk)* Add missing pnpm prepare directive
- Modify set account relation validation ([#713](https://github.com/ceramicnetwork/rust-ceramic/issues/713))
- Prevent panic on duplicate tracing initialization ([#718](https://github.com/ceramicnetwork/rust-ceramic/issues/718))
- Improved docs and logging for …
=> chore: version v0.55.0

event-svc/src/event/service.rs, event-svc/src/event/validator/event.rs, event-svc/src/store/sql/access/event.rs
=> fix: fetch unvalidated time proofs for conclusion events

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Fetch unvalidated time proofs for conclusion events ([#723](https://github.com/ceramicnetwork/rust-ceramic/issues/723))
=> chore: version v0.55.1

one/src/daemon.rs, one/src/lib.rs, one/src/startup.rs
This PR implements a new CLI flag `--extra-interests` (and envvar `CERAMIC_ONE_EXTRA_INTERESTS`) to automatically register node interests when starting the daemon, eliminating the need for manual API calls after startup.
- New CLI argument `--extra-interests`, accepting comma-separated stream/model IDs
- New startup module `one/src/startup.rs` to orchestrate daemon configuration tasks tangential to the startup process
- Integration:
- Uses the existing `InterestService`
- Uses the same pattern as the `/ceramic/interests` API handler
- Processes interests early in daemon startup, after services init but before P2P setup
- Optional flag with empty default
- Stream ID format and multibase decoding validation
- Descriptive errors for invalid inputs + handling of failures
- Logging for …
=> feat: allow configuring daemon with extra interests

CHANGELOG.md, Cargo.lock, Cargo.toml, api-server/Cargo.toml, api-server/README.md, api-server/api/openapi.yaml, api-server/src/lib.rs, api/ceramic.yaml, kubo-rpc-server/Cargo.toml, kubo-rpc-server/README.md, kubo-rpc-server/api/openapi.yaml, kubo-rpc-server/src/lib.rs, kubo-rpc/kubo-rpc.yaml
- Allow configuring daemon with extra interests ([#734](https://github.com/ceramicnetwork/rust-ceramic/issues/734))
- *(sdk)* Use correct controller during stream creation ([#724](https://github.com/ceramicnetwork/rust-ceramic/issues/724))
- *(sdk)* Set correct unique value for mids with set relation ([#730](https://github.com/ceramicnetwork/rust-ceramic/issues/730))
- Aggregator cache flush on shutdown ([#735](https://github.com/ceramicnetwork/rust-ceramic/issues/735))
- *(sdk)* Version v0.11.0 ([#727](https://github.com/ceramicnetwork/rust-ceramic/issues/727))
- *(sdk)* Version v0.12.0 ([#731](https://github.com/ceramicnetwork/rust-ceramic/issues/731))
=> chore: version v0.56.0
